### ISSUE TITLE
GraphQLInterface across Maven projects (heisenbug)

### ISSUE THREAD

**Issue by psgliniecki** [leangen/graphql-spqr#111]
So the bug I am getting is a bit weird. My setting is:

- it's a Spring Boot app;

- I have a maven project A where I build GraphQLSchema with GraphQLSchemaGenerator and AnnotatedResolverBuilder;

- service singletons are in project A;

- I have a maven project B where I keep the return classes for service singletons;

- there is an abstract class SomeAbstractObj annotated with GraphQLInterface with implementationDiscovery=true and two child classes with GraphQLType annotations that is used as a field in some return type.

The following happens: 

- when I compile the project with simple 'mvn clean project' the subclasses **aren't discovered** but...

- when I use a Debug run in Spring Tool Suite the child classes **are there**. 

I already tried with packages on annotation, basePackages specified globally and also .withNestedResolverBuildersForType(...). Also, when I put the return types to the same project it works OK - unfortunately that is costly in my particular case.

**Here's another twist**: I have some abstract superclasses that are used withOperationsFromSingleton(Object serviceSingleton, Type beanType) with the same multi-project structure and those work perfectly fine.  

Is it possible there's some race condition in the lib? If so, can you tell where? Is there a difference in processing between discovered classes and those directly passed trough withOperationsFromSingleton - maybe there's a way to pass class to the same processing but in a different way?

I would look for it but in the Debug mode that I use there is no bug to begin with... x)

**Comment by kaqqao** [comment]
There should be race conditions because the schema building process never creates any threads i.e. all the work (including the slow classpath scanning) is performed sequentially in the same thread...

But, the scanning depends on both the classpath itself and the classloaders used, and these are likely different in your 2 cases. I actually have no idea how are submodules loaded during a Maven build 😟 

These classloaders are asked to try finding the implementations:

* `Thread.currentThread().getContextClassLoader()`
* `superClass.getClassLoader()` (`superClass` is the one with `@GraphQLInterface`)
* `ClassFinder.class.getClassLoader()`
* `ClassLoader.getSystemClassLoader()`

If Maven loads separate modules with separate classloader, maybe none of the listed classloaders in module A is able to load a class from module B.

I'll start experimenting on my end (what a funky thing to debug!), and it may be good if you try the following:

* Enable TRACE logging for `io.leangen.graphql.util.classpath.ClassFinder` (or all of `io.leangen`), and see if what is difference in the output between the 2 different cases
* Add a `System.out.println` somewhere where the schema is being built that prints the (stringified) values of the above classloaders, and again see the differences between the cases

**Comment by kaqqao** [comment]
Oh, btw, this shouldn't actually be a problem once you actually deploy/run the application, only while running a test during a Maven build, for example. Is this corresponding with what you're experiencing?

Also, you can of course replace auto discovery with an explicit list of implementations, at least until I figure out if I can improve this.

**Comment by kaqqao** [comment]
Tried reproducing it, but with no success :(

I have 2 modules: A and B. An interface (`Iface`) is in A, the implementation (`IfaceImpl`) and a service (returning `Iface`) are in B. The schema generating code is in B as well. I have a test that creates a schema, with auto discovery, run via Maven (`mvn clean package`) and it passes.

Unfortunately, this means whatever is making your setup special is somewhere deeper. And it almost certainly involves multiple classloaders with tricky relations. Are you maybe deploying an EAR or something complex like that? Make sure you don't have the same class loaded twice by different loaders (this can happen in complex structures by accidentally having the same JAR/class in 2 locations).

Any chance you could try reproducing it on a dummy project?

**Comment by kaqqao** [comment]
One thing that could be very helpful is to try getting the actual classpath that Maven uses. This is normally done via the `dependency:build-classpath` goal. See some examples [here](https://stackoverflow.com/questions/16655010/in-maven-how-output-the-classpath-being-used/50368537#50368537).
You can also see get it from the log, there's an example on the same link.

Btw, did you maybe get to try something? Made some progress?

**Comment by kaqqao** [comment]
I see you're using Spring's `ClassPathScanningCandidateComponentProvider` which is likely smarter/more powerful than what SPQR has built-in, and I'd expect it work even if you scanned other packages. Since autodiscovery seems to be in popular use, I should probably swap the current implementation for something based on a more powerful library.... If you come up with a way to reproduce the issue, I'd be very grateful, as that would allow me to experiment. Even if you just get some new insights, please do post back.

Btw, you _may_ want to use `ClassUtils.forName` instead of `Class.forName` as it uses the thread-contextual classloader which is _usually_ the correct one in most app servers. Classloading in Java is a total mess, and you can never tell what loader you should be using.
