### ISSUE TITLE
How to map complex object lists?

### ISSUE THREAD

**Issue by eriveltonfacundo** [leangen/graphql-spqr#113]
`@Getter @Setter`
`@EqualsAndHashCode(of="id", callSuper=false)`
`public class Car {`
`	private Long id;`
`	private String description;`
`}`

`public class Cars {`
`	private List<Car> cars;`
`}`
Validation error of type SubSelectionRequired: Sub selection required for type null of field cars @ 'Cars/cars

**Comment by kaqqao** [comment]
Does `Cars` really have no public fields/properies? That's unlikely to work.

What query are you trying to execute?
And how do you setup the generator?

Btw, object lists are most definitely working as that's a very basic case. So the problem is either with the configuration somewhere or with Lombok. SPQR is generally not very Lombok-friendly as it doesn't look at private fields/methods, so if you need any annotations you'll have to work around that fact. But in this example there's no annotations, so it should work.

**Comment by eriveltonfacundo** [comment]
`I will do the test removing lombok, but my scenario is this:

@Getter @Setter
@EqualsAndHashCode(of="id", callSuper=false)
public class Car {
	private Long id;
	private String description;
}

@Getter @Setter
public class Dealership {
	private List<Car> cars;
}

{ 
	dealership(id:1) {
		cars{
			id,
			description
		}
	}
}

GraphQL.newGraphQL(new GraphQLSchemaGenerator()
                .withTypeTransformer(new DefaultTypeTransformer(true, true))
                .withBasePackages(ApiModel.class.getPackage().getName())
                .withOperationBuilder(new DefaultOperationBuilder(DefaultOperationBuilder.TypeInference.LIMITED))
                .withOperationsFromSingleton(graphQLService).generate())
                .build();

@GraphQLQuery(name = "dealership")
public Dealership cars(@GraphQLArgument(name = "id") Long id) {
	return dealershipService.findById(id);
}

"message": "Validation error of type SubSelectionRequired: Sub selection required for type null of field cars @ 'dealership/regimesDoPcarsroduto'",`

**Comment by kaqqao** [comment]
Any news on this?

**Comment by eriveltonfacundo** [comment]
I discovered the problem, when I was mounting the request I was not sending the complex object fields. thanks!!
