### ISSUE TITLE
java.sql.Date issue.

### ISSUE THREAD

**Issue by andriassundskard** [leangen/graphql-spqr#114]
Hi,

I am using version 0.9.7.

I get the following exception when my query contains a java.sql.Date field.

> Caused by: java.lang.UnsupportedOperationException: null
> 	at java.sql.Date.toInstant(Date.java:304)
> 	at io.leangen.graphql.util.Scalars.lambda$static$2(Scalars.java:153)
> 	at io.leangen.graphql.util.Scalars$5.serialize(Scalars.java:249)
> 	at io.leangen.graphql.util.Scalars$5.serialize(Scalars.java:244)
> 	at graphql.execution.ExecutionStrategy.completeValueForScalar(ExecutionStrategy.java:482)
> 	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:365)
> 	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:332)
> 	at graphql.execution.ExecutionStrategy.lambda$resolveField$0(ExecutionStrategy.java:172)
> 	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
> 	... 91 common frames omitted

Any idea what I'm doing wrong?

**Comment by kaqqao** [comment]
Hmm, it seems your method/argument/field is typed as `java.util.Date` but is really a `java.sql.Date` instance. As a result SPQR treats it as `java.util.Date` which has a `toInstant` method.

Seeing that the inheritance between these 2 classes is a hack that is still in Java only because it can't be safely removed, it would be better not to rely on it at all, and treated these classes as completely unrelated. I.e. never substitute `java.sql.Date` for `java.util.Date` and instead have your arguments/return types always be exact. This will fix your issue with SPQR as well.

But, for the sake being full-proof, I'll fix this in SPQR 0.9.8 as well.

**Comment by andriassundskard** [comment]
Thanks for helping me out on this! My field was indeed typed as `java.util.Date` but I got a `java.sql.Date` from the JDBC driver. I added a few casts and now everything is fine.

**Comment by kaqqao** [comment]
Closed as #136
