### ISSUE TITLE
Add support to make Page<T> fields non nullable

### ISSUE THREAD

**Issue by MrHus** [leangen/graphql-spqr#127]
Currently when using `Page<T>` as the return type the following type is generated:

<img width="155" alt="screen shot 2018-07-05 at 16 15 59" src="https://user-images.githubusercontent.com/22608/42328515-bd9d6ca0-806e-11e8-9387-418608c583e9.png">

I would like the Page's first, last, content etc etc to be defined as non nullable, like this:

```
first: Boolean!
last: Boolean!
content: [Type!]!
```

Can you add support for this feature, or if it already exists how to achieve this.

**Comment by kaqqao** [comment]
Something is _very_ wrong with your setup. Methods returning a `Page<T>` should not be mapped as you describe, but as proper Connections, as described by the [Relay Cursor Connections Specification](https://facebook.github.io/relay/graphql/connections.htm).

This also means your arguments _should_ (don't exactly _have to_, see below) match exactly the arguments specified there (plus optional extra arguments):

>Forward pagination arguments
>To enable forward pagination, two arguments are required.

>`first` takes a non‐negative integer.
>`after` takes the cursor type as described in the cursor field section.

>Backward pagination arguments
>To enable backward pagination, two arguments are required.

>`last` takes a non‐negative integer.
>`before` takes the cursor type as described in the cursor field section.

`after` and `before` are `String`s, and `first` and `last` and `Int`s. So you can ask e.g. _*first* 10 items *after* item 'abc123'_ or _*last* 15 items *before* the item 'abc123'_.
I'm saying this because I see you have `first` and `last` as `Boolean`, and no `before` or `after`.

That said, only the arguments specified above `first`, `last`, `after` and `before`
 must match in type with the spec, but they don't have to be present. If you just have some _other_ arguments, they can be anything you want. E.g.

```java
@GraphQLQuery
public Page<Item> items(@GraphQLNonNull boolean something, @GraphQLNonNull boolean somethingElse) {
    return PageFactory.createOffsetBasedPage(...); //or create your own instance
}
```

This should produce an `ItemConnection` type as the result.

I still wonder how you got the mapping you got. Can you exemplify your method and generator setup? Also, what version of SPQR are you on?

**Comment by MrHus** [comment]
This is the code which creates the _faulty_ page:

```java
@GraphQLNonNull
    @GraphQLQuery(name = "allPokemon", description = "Get a Page of pokemon")
    public Page<@GraphQLNonNull Pokemon> allPokemon(
            @GraphQLNonNull @GraphQLArgument(name = "page") int page,
            @GraphQLNonNull @GraphQLArgument(name = "size") int size,
            @GraphQLArgument(name = "query", defaultValue = "") String query) {
        return pokemonService.findAll(PageRequest.of(page, size), query);
    }
```
The pokemonService's findAll is defined as such:

```java
public Page<Pokemon> findAll(Pageable pageable, String query) {
  return pokemonRepository.findAllByNameContainingIgnoreCase(pageable, query);
}
```

Also I do not understand your PageFactory.createOffsetBasedPage example, what is the first argument supposed to be. In code it is defined as `List<N> nodes` what are the nodes in this context: a list of all Pokemon in the database?

**Comment by MrHus** [comment]
I've solved my problem by creating my own Page like type for the solve purpose so I could make the content non-null and add doc comments.

Here is the code:

```java
public class GraphQLPage<T> {

    @GraphQLNonNull
    @GraphQLQuery(name = "content", description = "The content of the page")
    public final List<T> content;

    @GraphQLNonNull
    @GraphQLQuery(name = "last", description = "Whether or not this page is the last page of the collection")
    public final boolean last;

    @GraphQLNonNull
    @GraphQLQuery(name = "totalElements", description = "The total number of elements that exist in the collection")
    public final long totalElements;

    @GraphQLNonNull
    @GraphQLQuery(name = "totalPages", description = "The total number of pages that the collection has")
    public final int totalPages;

    @GraphQLNonNull
    @GraphQLQuery(name = "size", description = "The max number of items in the content of this page")
    public final int size;

    @GraphQLNonNull
    @GraphQLQuery(name = "number", description = "The which page of totalPages this is")
    public final int number;

    @GraphQLNonNull
    @GraphQLQuery(name = "first", description = "Whether or not this page is the first page in the collection")
    public final boolean first;

    @GraphQLNonNull
    @GraphQLQuery(name = "numberOfElements", description = "The actual number of content elements in this page")
    public final int numberOfElements;

    public GraphQLPage(
            List<T> content, 
            boolean last, 
            long totalElements, 
            int totalPages, 
            int size, 
            int number, 
            boolean first, 
            int numberOfElements
    ) {
        this.content = content;
        this.last = last;
        this.totalElements = totalElements;
        this.totalPages = totalPages;
        this.size = size;
        this.number = number;
        this.first = first;
        this.numberOfElements = numberOfElements;
    }

    public static <T> GraphQLPage from(Page<T> page) {
        return new GraphQLPage(
                page.getContent(),
                page.isLast(),
                page.getTotalElements(),
                page.getTotalPages(),
                page.getSize(),
                page.getNumber(),
                page.isFirst(),
                page.getNumberOfElements()
        );
    }
}
```
It is not as fancy as using a cursor but it gets the work done. 

I'm still curious on how the PageFactory. createOffsetBasedPage works.

**Comment by kaqqao** [comment]
Ah, we were talking about different `Page` classes. You were talking about `org.springframework.data.domain.Page` (as you noted above) and I was thinking of `io.leangen.graphql.execution.relay.Page`, which is what `PageFactory.createOffsetBasedPage` produces.

SPQR itself has no special mappings for framework-specific types (such as Spring Data ones you're dealing with), as it has to remain agnostic, but I will release a few extra modules for easier handling of popular frameworks. The module for Spring is naturally the priority as we need it for the [SPQR Spring Boot Starter](https://github.com/leangen/graphql-spqr-spring-boot-starter).

In the meantime, you can always create a custom `TypeMapper` and/or `InputConverter`/`OutputConverter` yourself. But if you're happy with the solution you have, that's also fine.

As for the `io.leangen.graphql.execution.relay.Page` and `PageFactory.createOffsetBasedPage`, it's for producing [Relay Cursor Connections Specification] compliant (https://facebook.github.io/relay/graphql/connections.htm) pages. You don't really have to care about this unless you want to use Relay's pagination features or simply like the spec.

The way `PageFactory.createOffsetBasedPage` works is by wrapping a simple collection of items into a Relay-style page, where the offset is used as the cursor. This makes sense only if you database doesn't support cursor based pagination or using is undesirable for some reason.

Example:

```java
@GraphQLQuery
public Page<Book> books(int first, String after) {
    int offset = Integer.parseInt(after); //parse the offset from what's supposed to be the cursor
    List<Book> books = dataBase.query("SELECT FROM Books LIMIT :first OFFSET :offset"); //Query the DB
    return PageFactory.createOffsetBasedPage(books, totalCount, offset); //wrap the result into a Page
}
```

Notice that `after` has to be a String because the spec defines it that way, as it's intended to be used as a generic cursor. We're sort of _abusing_ it here by making it the offset.
Also notice you need to somehow acquire the `totalCount` of `Book` somehow (which is possible in many relational DBs without running a separate query using the window functions).

**Comment by kaqqao** [comment]
Open an issue about this in the SPQR Spring Boot Starter project.
