### ISSUE TITLE
Why @Transient makes ignore the property for GraphQL ?

### ISSUE THREAD

**Issue by tufgupmi** [leangen/graphql-spqr#148]
When marking @Transient (javax.persistence) for a property then is not include in the GraphQLSchema. Why ? I want a variable in the GraphQLSchema but i don't want to persist it.

**Comment by tufgupmi** [comment]
Ok, if i make then the getter methos as @GraphQLQuery then it's included.

**Comment by kaqqao** [comment]
You must talking about input (not output) types, correct?

The only explanation I can come up with is that Jackson decided that field isn't deserializable.

Input objects must be deserialized and a library is needed for that. Thus only the fields the given library is able to deserialize are going to get mapped (no point in mapping a field if its value will never be usable). SPQR works with Jackson and Gson out of the box (which have wildly different ideas about what's deserializable), preferring Jackson. And I presume Jackson for some reason has rules about transient fields.

That said, you have multiple ways to influence all this:

1. Replace the `InputFieldBuilder` (currently called `InputFieldDiscoveryStrategy` but getting renamed and simplified in 0.9.8), and potentially not involve Jackson/Gson in the decision at all. This lets you make all the decisions yourself, but you also assume all the responsibility for making the values deserializable.

2. Supply a custom `InclusionStrategy` and filter out the discovered fields. This lets you exclude some fields, but that is insufficient in your case, as you're trying to include otherwise ignored fields.

3. Try to influence the fields using annotations (either Jackson's or SPQR's)

4. Configure Jackson differently, which is doable via options exposed by `JacksonValueMapperFactory`.

In 0.9.8, the now somewhat complex 1st option becomes simplified, and much more usable. But in your case, I'd stick with options 3 or 4. I'm not sure of Jackson exposes some options for configuring the behavior around transient fields, but I'd be surprised if it didn't.

**Comment by kaqqao** [comment]
Did you get this sorted out?

**Comment by tufgupmi** [comment]
Hello, 

Yes, as i explain above if you annotated the getter of a Transient filed with @GraphQLQuery then it's included in the schema,

Thanks

**Comment by kaqqao** [comment]
Ok, thanks for the update. Closing this.
