### ISSUE TITLE
Nested @GraphQLNonNull not working

### ISSUE THREAD

**Issue by benneq** [leangen/graphql-spqr#159]
Im trying to use this:

```
@Component  // Spring annotation
public class MyService {
	@GraphQLQuery
	public @GraphQLNonNull Collection<@GraphQLNonNull MyData> foo(MyFilter filter) {
		// ...
	}
}
```

with:
```
@Data  // Lombok annotation
public class MyFilter {
	@GraphQLNonNull   // <- this is not working
	private String foo;
}
```

`/graphiql` shows `String` instead of `String!`. And when executing the query it allows `foo` to be null.

**Comment by kaqqao** [comment]
SPQR never looks at private elements, so annotating a private field will not work (with the exception of `@GraphQLInputField` with Jackson, but that is because Jackson takes private fields into account, not SPQR).
This makes it not Lombok-friendly, I'm aware, but that's the current situation.
You can of course add your own `ResolverBuilder` that _will_ take private fields into consideration, but it is a significant amount of work. It is easier to add an explicit getter with the annotation.

I'll look into Lombok support for version 0.9.9. Track #160 for progress.

**Comment by kaqqao** [comment]
Thanks for the kind words! 😊

GraphQL SPQR is based on graphql-java, as that's the only GraphQL implementation in Java.

I'm also sort of a (barely active) member of the graphql-java team. But the servlet and Spring Boot projects are totally different teams, only sharing the repo for historical reasons. Those projects are different in their goal from SPQR, in that they cater to schema-first development while SPQR is code-first.

**Comment by kaqqao** [comment]
Btw, are you by any chance using [SPQR Spring Boot Starter](https://github.com/leangen/graphql-spqr-spring-boot-starter)?

**Comment by benneq** [comment]
They also have a code-first part using `graphql-java-annotations`: https://github.com/graphql-java/graphql-java-annotations
Their test's are showing how to use it: https://github.com/graphql-java/graphql-java-annotations/blob/master/src/test/java/graphql/annotations/GraphQLInputTest.java#L332-L367
```
GraphQLSchema schema = newSchema().query(GraphQLAnnotations.object(QuerySameNameWithChildren.class)).build();
```
They inspect some class for their annotations and then generate the GraphQLSchema. This should be pretty similar to your project.

--- 

Yes I'm using your Spring Boot Starter. Opened an issue there today, too 😄
