### ISSUE TITLE
Help with @Batched query

### ISSUE THREAD

**Issue by frieck** [leangen/graphql-spqr#178]
Hello!

First of all thanks for all the great job you guys are doing with SPQR!
I'm having trouble while trying to use the `@Batched` Annotation....

I'm creating a service where I can search for users and all their comments. Here is the code to the User Query:
```java
@GraphQLQuery(name = "listAllUserData") 
public Page<UserData> findAll(
        @GraphQLArgument(name = "page", defaultValue = "1") Number page,
	@GraphQLArgument(name = "limit", defaultValue = "10") Number limit,
	@GraphQLArgument(name = "sort", defaultValue = "id", defaultValueProvider = DefaultSortingProvider.class) SortField sorting,
	@GraphQLArgument(name = "filter", defaultValueProvider = DefaultFilterProvider.class) UserData filter) {
	return userDataRepository.findAll(PageRequest.of(page.intValue() - 1, limit.intValue(), Sort.Direction.fromString(sorting.getDirection().toString()), sorting.getName()));
}
```

and here is the the query to return comments: 
```java
@Batched
@GraphQLQuery(name = "comments")
public List<CommentsDTO> getComments(@GraphQLContext List<UserData> users) {
	List<CommentsDTO> comments = new ArrayList<>();
	List<Long> ids = users.stream().map(UserData::getId).collect(Collectors.toList());
	return commentsService.findByIds(ids);
}
```

And here is the query I'm running: 
```graphql
{
  listAllUserData(page: 1, limit: 5) {
    first
    last
    totalElements
    totalPages
    content {
      id
      nmFirst
      nmLast
      gender
      dtBirth
      active
      comments {
        text
        date
      }
    }
  }
}
```
This query is returning an error:
```json
"errors": [
    {
      "message": "Exception while fetching data (/listAllUserData/content[0]/comments) : java.lang.ClassCastException@1b273786",
      "locations": [
        {
          "line": 14,
          "column": 7
        }
      ],
      "path": [
        "listAllUserData",
        "content",
        0,
        "comments"
      ]
    },
...
```

I might be doing something wrong, but I cant find any documentation about the `@Batched` annotation.
Can you guys help me?

**Comment by kaqqao** [comment]
You probably forgot to use `BatchedExecutionStrategy`. `@Batched` doesn't work otherwise.
But, the the problem here is that graphlq-java deprecated `BatchedExecutionStrategy` a while ago, and will likely remove it in the future.

The current approach is to use [DataLoader](https://github.com/graphql-java/java-dataloader) for this instead.

**Comment by frieck** [comment]
Thanks @kaqqao!

Is there any relation between the DataLoader and the `@Batched` annotation? Do I still need to use the annotations? Do you have any simple example of this approach?

Thanks again,

**Comment by kaqqao** [comment]
No, `@Batched` is only relevant in the context of `BatchedExecutionStrategy`. No relation to DataLoader.

As for the usage, check the official docs, there's no real difference between using it with or without SPQR.

The general steps are:

1) Create your `BatchLoader`s.
```java
DataLoaderRegistry loaders = ...; //initialize your loaders, usually per request

GraphQL graphQL = GraphQL.newGraphQL(schemaFromSPQR)
          .instrumentation(new DataLoaderDispatcherInstrumentation(loaders)) //don't forget this! also, usually per request
          .build();
```

or have a _template_ `GraphQL` instance that you transform per request:

```java
graphQL = graphQL.transform(builder -> builder.instrumentation(new DataLoaderDispatcherInstrumentation(loaders)));
```

The, when executing an operation:
```java
graphQL.execute(ExecutionInput.newExecutionInput()
         .query(operation)
         .context(loaders) //use the loaders as context, or as a part of the context
         .build());
```
Then in your bean:
```java
@GraphQLQuery
public CompletableFuture<Item> item(@GraphQLArgument(name = "id") Long id, @GraphQLRootContext DataLoaderRegistry loaders){ 
      return loaders.getDataLoader("items").load(id); //load using the injected DataLoader
}
```
As of DataLoader 2.1, there's an option of supplying a _context provider_ to the `BatchLoader` so that you can easily make use of security context, DB connection, or things like that in your `BatchLoader`s without having to recreate them on each request. See the official docs for examples.

SPQR might eventually include some nice helpers for DataLoader (e.g. to discover `BatchLoaders` by annotation), but that will be post v1.0

**Comment by frieck** [comment]
Thanks again @kaqqao!
Appreciate your help!
