### ISSUE TITLE
How to allow only specific fields to be queried?

### ISSUE THREAD

**Issue by liester** [leangen/graphql-spqr#187]
I've done some digging through the docs and the fact that I'm unable to find any information makes me feel like either it isn't supposed to be done or its so obvious no one has asked.

I'm using spring boot.  I have a working example of a spring bean exposed via graphql, which is fantastic.  I am doing that with this code:

```java
  @Bean
  GraphQLSchema schema() {
    return new GraphQLSchemaGenerator()
            .withOperationsFromSingleton(testService, testServiceImpl.class)
            .generate();
  }
```

I then annotate one of the methods in the testServiceImpl.class with `@GraphqlQLQuery` to expose it:
```java
@GraphQLQuery(name="getStuff")
  @Override 
  public Stuff getStuff() {  
    return new Stuff();  
  }
```

```java
public class Stuff {
    private Integer id= 1;
    private String name = "Levi";
    private LocalDateTime localDateTime = LocalDateTime.now();

    public Integer getId() {
      return id;
    }

    public String getName() {
      return name;
    }
  }
```

It appears that by default if there is a getter then the field will be exposed as query-able via graphql.  If I were to create a schema by hand I could specify that I don't want `name` to be exposed.

I'm guessing there is a way to do this with SPQR but I'm not having much luck finding it and thought I would ask people more knowledgeable about this than I am.

How can I `hide` fields so they don't appear in graphiql and are valid in the qraphql request?

**Comment by kaqqao** [comment]
What gets exposed depends on a `ResolverBuilder` in use.

SPQR distinguishes between top level builders and _nested_ builders, where top level builders only apply to beans/types directly registered with the generator (`withOperationsFrom`) and nested builders apply to everything else discovered along the way.

This is because the deeper you go, the less control you generally have (running into JVM core or framework classes) and the ability to explicitly annotate stuff is usually not there.

The default nested resolver builders are `AnnotatedResolverBuilder` (mapping explicitly annotated stuff) and `BeanResolverBuilder` (mapping public getters). If any of these decides to map a method - it gets exposed.

You can control this behavior in various ways. For starters, you can explicitly ignore a field using `@GraphQLIgnore`:

```java
@GraphQLIgnore
public Integer getId() {
    return id;
}
``
You can override the nested builders globally:

```java
generator.withNestedResolverBuilders(new AnnotatedResolverBuilder());
```

Or you can even register specific builders for one type only:

```java
generator.withNestedResolverBuildersForType(Stuff.class, new AnnotatedResolverBuilder());
```

If you're using SPQR Spring Boot starter, you can also apply a builder to a single bean only using the `@WithResolverBuilder` annotation. (Btw, of you're using the starter, you don't even need to generate the schema yourself, just annotate a bean with `@GraphQLApi` and all such beans will automatically be exposed 😉).

Further more, you have an option to add a filter (or other options) to a `ResolverBuilder` using

```java
new BeanResolverBuilder().withFilter(.. )
```

I'm planning to enrich this API even further soon.

**Comment by liester** [comment]
Hot damn, that `@GraphQLIgnore` worked just like it wanted it to.  Is that somewhere in the documentation and I just missed it or not yet documented?

Also the `@GraphQLApi` would have been very convenient but I ran into issues with that.  I get this error:
```Caused by: io.leangen.graphql.metadata.exceptions.TypeMappingException: The registered object of type com.proxibid.taz.api.v1_0.phone.verification.TeleSignPhoneVerificationService$$EnhancerBySpringCGLIB$$e664154e appears to be a dynamically generated proxy, so its type can not be reliably determined. Provide the type explicitly when registering the bean. For details and solutions see https://github.com/leangen/graphql-spqr/wiki/Errors#dynamic-proxies```

I ended up having to do this:
```java
@Bean
  GraphQLSchema schema() {
    return new GraphQLSchemaGenerator()
            .withOperationsFromSingleton(phoneVerificationService, TeleSignPhoneVerificationService.class)
            .generate();
  }
```

But that is for another issue (question) so I will close this one with a resounding success!
Thank you for you timely response @kaqqao
