### ISSUE TITLE
@GraphQLIgnore with AnnotatedResolverBuilder

### ISSUE THREAD

**Issue by cmdavinder** [leangen/graphql-spqr#189]
Hi there, 

I am trying to get control of fields that are exposed in schema generated by SPQR. After Switching on AnnotatedResolverBuilder I get below error when I load up GraphiQL.

**Error: Post fields must be an object with field names as keys or a function which returns such an object.**

Here's the code for what I tried. 

>     @Bean
>     public GraphQLSchema schema() {
>         return new GraphQLSchemaGenerator().withResolverBuilders(new AnnotatedResolverBuilder())
>                                            .withOperationsFromSingleton(discussionResolver)
>                                            .withOperationsFromSingleton(postResolver)
>                                            .withNestedResolverBuilders(new AnnotatedResolverBuilder())
>                                            .generate();
>     }
> 

>
> @Document(collection = "post")
> @Getter
> @Setter
> @NoArgsConstructor(access = AccessLevel.PACKAGE)
> @AllArgsConstructor(access = AccessLevel.PACKAGE)
> @Builder
> @EqualsAndHashCode(of = "id", callSuper = false)
> @ToString
> public class Post implements Persistable<String> {
> 
>     @Id
>     @GraphQLQuery
>     private String id;
> 
>     @NonNull
>     @GraphQLIgnore
>     private String discussionId;
> 
>     @NonNull
>     @GraphQLQuery
>     private String content;
> 
>     @Builder.Default
>     @GraphQLQuery
>     private List<Reply> replies = new LinkedList<>();
> 
>     @Builder.Default
>     @GraphQLQuery
>     private Long likes = 0L;
> 
>     @GraphQLQuery
>     @CreatedDate
>     @DateTimeFormat(iso = DATE_TIME)
>     private LocalDateTime createdAt;
> 
>     @GraphQLQuery
>     @LastModifiedDate
>     @DateTimeFormat(iso = DATE_TIME)
>     private LocalDateTime lastModifiedAt;
> 
> 
>     /**
>      * Adds a {@link Reply} to this {@link Post}
>      *
>      * @param reply
>      */
>     public void addReply(Reply reply) {
>         this.replies.add(reply);
>     }
> 
>     /**
>      * Removes a {@link Reply} from this {@link Post}
>      *
>      * @param reply
>      */
>     public void removeReply(Reply reply) {
>         this.replies = this.replies.stream()
>                                    .filter(r -> !reply.getId().equals(r.getId()))
>                                    .collect(Collectors.toCollection(LinkedList::new));
>     }
> 
>     @GraphQLIgnore
>     @Override
>     public boolean isNew() {
>         return !Optional.ofNullable(this.id)
>                         .isPresent();
>     }
>

**Comment by kaqqao** [comment]
This means no fields got mapped.
The reason is most certainly Lombok. The SPQR annotations you put on private fields are ignored, as SPQR never looks at private members, and there's no annotations on the generated getters.
In general, SPQR does not play well with Lombok. I plan to do something about it in the near future, though.

Right now, it is possible to create a custom `ResolverBuilder` that takes private fields into account, but it's honestly less work to add explicit getters where you need them.

Btw, why did you need to override the default nested resolver builder? `@GraphQLIgnore` works in any case (as long as it's on a public member), and you can also add custom filters to any of the resolver builders.

**Comment by cmdavinder** [comment]
Thanks for quick response. Appreciate it. I think I can get it to work from here. 

I had overridden nested resolver builder in an attempt to get GraphQLNonNull to work. It works after only adding the Getter manually. Even below trick didn't work. :)

>     @GraphQLQuery
>     @Getter(onMethod_ = @GraphQLNonNull)
>     private String title;
>

**Comment by kaqqao** [comment]
It didn't work because `GraphQLNonNull` isn't applicable on methods, but on types. I.e. you put it on the return type itself, not on the whole method.

One way to workaround this with Lombok would be to use a method-level annotation instead. SPQR recognizes a few different ones in addition to `@GraphQLNonNull`, you can see the full list [here](https://github.com/leangen/graphql-spqr/blob/master/src/main/java/io/leangen/graphql/generator/mapping/common/NonNullMapper.java#L45).

**Comment by cmdavinder** [comment]
Thanks. I figured that out yesterday and got it working. Pretty cool to know you support @NonNull from javax too.
