### ISSUE TITLE
Possible bug converting date scalars

### ISSUE THREAD

**Issue by tufgupmi** [leangen/graphql-spqr#196]
Hello, 

When you convert data scalar you are using UTC as TimeZone

In class Scalars
```
   public static final GraphQLScalarType GraphQLSqlDate = temporalScalar(java.sql.Date.class, "SqlDate", "a SQL compliant local date",
            s -> java.sql.Date.valueOf(LocalDate.parse(s)), i -> java.sql.Date.valueOf(i.atZone(ZoneOffset.UTC), d -> d.toLocalDate().toString());
```

If you send a date using miliseconds, for example 581551200000 this corresponds to 1988-06-06 GMT+02:000, but in UTC is 1988-06-05. 

For example is a use a default convert to parse 1988-06-06 to miliseconds is 581551200000, but after graphql-spqr processing is 1988-06-05

I think you should use the default timeZone so, won't be problems.

In class Scalars
```

   public static final GraphQLScalarType GraphQLSqlDate = temporalScalar(java.sql.Date.class, "SqlDate", "a SQL compliant local date",
            s -> java.sql.Date.valueOf(LocalDate.parse(s)), i -> java.sql.Date.valueOf(i.atZone(TimeZone.getDefault().toZoneId()), d -> d.toLocalDate().toString());
```

**Comment by kaqqao** [comment]
This is intentional. Using the server's default timezone will often be of no value (and potentially very confusing!) to the client, as the client could be in a different time zone. Imagine the client and the server in different countries with different daylight saving rules. What if different clients are in different time zones? Interpreting the values from the server would be absolute nightmare.
For this reason, the default scalars always use the most portable format - ISO 8601 in UTC. It is the job of the client then to transform the UTC time into whatever it is they need (the user's default time zone?). The client must also make sure to send only UTC times to the server.
If you _really_ want it, you can provide custom scalar mapping to override this, but that's generally a very bad idea as it makes internationalization insanely difficult.

**Comment by tufgupmi** [comment]
Hello

Thank you for response. 

My problem is that is not the client who send the miliseconds, is the own server. 

The client send a graphQL with a date (no time zone as it's not needed), Then i have a graphqlapi with graphql-braid that transforms the GraphQL query into another and jackson transforms dates into miliseconds and do that in the timezone of the server and forward the graphql to the microservice that serves that specifc request. Then in the microservice as you use UTC i get a wrong date..

**Comment by awestwell** [comment]
Is there a way to for a Date to be of type Int instead of a Scalar? I ask as I want to be able to send epoch dates to the client instead of String formatted dates. Is this possible in SPQR? 

The Apollo client does not map Scalars currently. So I figured the best solution would be to send it as an Int :)

Thanks

Ash
