### ISSUE TITLE
Is it possible to distinguish between null fields and undefined fields ?

### ISSUE THREAD

**Issue by tufgupmi** [leangen/graphql-spqr#197]
Hello, 

Is there a way to know when a fields has been send with null or when a field has not been send in a mutation ?

For example i have mutation

```
updateUser(id: Int!, userRequest: UserRequestInput): User

input UserRequestInput {
  addresses: String
  birthDate: SqlDate
  countryId: Int
}
```

How can i distinguish between 

In this case i want to set address to null in DB

```
{
  address:  null
  birthDate: "1982-05-22", 
  countryId: 4
}

```
and 

In this case i want to not modify address in DB

```
{ 
  birthDate: "1982-05-22", 
  countryId: 4
}

```

What i receive in the service is always null in both cases. How can i diferentiate between them ?

**Comment by kaqqao** [comment]
I think the only way at this moment is to inject `ResolutionEnvironment` and check if the raw argument was provided.

```java
@GraphQLQuery
public String test(String address, @GraphQLEnvironment ResolutionEnvironment env) {
    if (address == null && env.dataFetchingEnvironment.containsArgument("address")) {
         // Was explicit null        
    }
    // Was omitted
}
```

This of course sucks... so I'll retrofit the `Optional` to enable a better way to deal with nulls in the near future.

**Comment by kaqqao** [comment]
I've added 2 changes to make this possible.

1. `ArgumentInjectorParams#isPresent` enables an `ArgumentInjector` to tell whether the value is present (either provided explicitly or by default) or not.

2. Arguments of type `Optional`, `OptionalInt`, `OptionalLong` and `OptionalDouble` will be injected with `null` if no value is present and with their respective empty value if `null` was provided explicitly or by default. The reason this logic is backwards is because both Jackson and Gson handle optionals in this manner (no clue _why_ though).

**Comment by gxs0onr** [comment]
Can you post a short example on how to use this new feature?

**Comment by kaqqao** [comment]
Let's say you have a method such as:

```java
@GraphQLMutation
public User createUser(String name, Address address) { ... }
```

You coukld change it to:

```java
@GraphQLMutation
public User createUser(String name, Optional<Address> address) { ... }
```

Now, for a query such as:

```graphql
mutation createUser {
  createUser(name: "Test", address: null) {
    ...
  }
}
```

the value of `address` in Java would be `Optional.empty`.
But the for:

```graphql
mutation createUser {
  createUser(name: "Test") {
    ...
  }
}
```
`address` object in Java would be `null`.
