### ISSUE TITLE
SPQR 0.9.8 renames queries without @GraphQLArgument

### ISSUE THREAD

**Issue by vburlion** [leangen/graphql-spqr#207]
Hi!

With the latest version of SPQR (0.9.8), we encounter an odd behaviour where one of our query is automatically renamed in the GraphQL schema.
This query:
`fun getCategories(): Set<Category>`
would create a `getCategories` query in the generated schema before 0.9.8, and is now renamed `categories`.
We think it's because this query doesn't have any `@GraphQLArgument`. Our other queries, that all have `@GraphQLArguments`, are not renamed.

We had to put an explicit name at the `@GraphQLQuery` level.

This issue also happens with our only mutation which - for obvious reasons - does have a `@GraphQLArgument`

Any insight as to why we observe this change? Is it a bug or a feature?

Thanks!

**Comment by kaqqao** [comment]
The logic for field naming is in `PropertyOperationNameGenerator` and it checks whether a method is a _getter_ and if so, strips away the `get` part.
If a method has an argument, it is no longer a _getter_, but just a regular method, hence the `get` stays.

That said, I'm not sure this makes sense... What would you expect to happen here?

**Comment by evader1337** [comment]
I have a question regarding this issue. Is the "get" now always dropped from any function name or just getters? I have a getSomething function (with one argument) and the get gets removed from the name. And like you said, how does one configure these settings?

**Comment by kaqqao** [comment]
Yes, _get_ is now always dropped. The reason is explained above: adding a parameter shouldn't have side-effects of changing the operation name. If you still desire such behavior, you can customize the name generation:

```java
public class CustomOperationNameGenerator extends DefaultOperationNameGenerator {
    @Override
    public String generateQueryName(OperationNameGeneratorParams<?> params) {
        if (params.isMethod() && ClassUtils.isGetter((Method) params.getElement())) {
            return ClassUtils.getFieldNameFromGetter((Method) params.getElement());
        }
        return params.getElement().getName();
    }
}
```

and then:

```java
generator.withResolverBuilders(new AnnotatedResolverBuilder()
      .withOperationNameGenerator(new CustomOperationNameGenerator()))
```

Be aware that this specific API will change quite a bit in the next release, as `OperationNameGenerator` is now `OperationInfoGenerator` and is responsible for more then just generating the name. Additionally, it can now receive multiple elements (e.g. both the getter and the related field).

The equivalent in the new API would look like:

```java
public class CustomOperationInfoGenerator extends PropertyOperationInfoGenerator {
    @Override
    public String name(OperationInfoGeneratorParams params) {
        return Utils.extractInstances(params.getElement().getElements(), Method.class)
                .filter(ClassUtils::isGetter)
                .findFirst().map(ClassUtils::getFieldNameFromGetter)
                .orElse(null);
    }
}
```

and then e.g.:
```java
.withResolverBuilders(new AnnotatedResolverBuilder()
                        .withOperationInfoGenerator(new DefaultOperationInfoGenerator()
                                .withDelegate(new CustomOperationInfoGenerator())))
```

**Comment by kaqqao** [comment]
@evader1337
Deleted my previous answer (it was wrong), here's an update:

Yes, get is now always dropped. The reason is explained above: adding a parameter shouldn't normally have the side-effect of changing the operation name.
If you still desire such behavior, you can customize the name generation:

```java
public class CustomOperationNameGenerator extends AnnotatedOperationNameGenerator {
    @Override
    public String generateQueryName(OperationNameGeneratorParams<?> params) {
        if (params.isMethod() && ClassUtils.isGetter((Method) params.getElement())) {
            return ClassUtils.getFieldNameFromGetter((Method) params.getElement());
        }
        return super.generateQueryName(params);
    }
}
```
and then:
```java
generator.withResolverBuilders(new AnnotatedResolverBuilder()
                        .withOperationNameGenerator(new DefaultOperationNameGenerator()
                                .withDelegate(new CustomOperationNameGenerator())))
```
Be aware that this specific API will change quite a bit in the next release, as OperationNameGenerator is now OperationInfoGenerator and is responsible for more then just generating the name. Additionally, it can now receive multiple elements (e.g. both the getter and the related field).

The equivalent in the new API would look like:

```java
public class CustomOperationInfoGenerator extends AnnotatedOperationInfoGenerator {
    @Override
    public String name(OperationInfoGeneratorParams params) {
        List<? extends AnnotatedElement> elements = params.getElement().getElements();
        Optional<String> field = Utils.extractInstances(elements, Field.class).findFirst().map(Field::getName);
        Optional<String> getter = Utils.extractInstances(elements, Method.class).filter(ClassUtils::isGetter).findFirst().map(ClassUtils::getFieldNameFromGetter);

        return Utils.coalesce(super.name(params), Utils.or(field, getter).orElse(null));
    }
}
```
This is the same implementation as `PropertyOperationInfoGenerator` except for the `.filter(ClassUtils::isGetter)` part.
And then e.g.:
```java
generator.withResolverBuilders(new AnnotatedResolverBuilder()
                        .withOperationInfoGenerator(new DefaultOperationInfoGenerator()
                                .withDelegate(new CustomOperationInfoGenerator())))
```
