### ISSUE TITLE
Asking for fields of a subclass of an abstract class without defining their getter in abstract class.

### ISSUE THREAD

**Issue by Rashi-G** [leangen/graphql-spqr#234]
I have an abstract class called `ParentClass` -
```java
public class ParentClass {
    private int x;
    public void setx(int x) {
        this.x=x;
    }

    public int getx() {
        return x;
    }

    public abstract int gety();
}
```
I have a child class which extends above abstract class-
```java
public class ChildClass extends ParentClass {
    private int y;
    private int z;
    
    public void sety(int y) {
        this.y=y;
    }

    public int gety() {
        return y;
    }

    public void setz(int z) {
        this.z=z;
    }

    public int getz() {
        return z;
    }
}
```

Now in query, When I query for x and y, I get expected results probably because their getters are defined in abstract class. But when I query for z, I get query validation error('z' field undefined). 

Is there a way to ask for z's value in query without defining it's getter in abstract class?

**Comment by kaqqao** [comment]
Which of these is actually exposed? What does you query method look like?

**Comment by Rashi-G** [comment]
return type of my query is a result class.
public class result
{
private List <ParentClass> result1;
private int id;
//Then setters and getters for both
} 

Query --
query mainQuery
{
myQuery
{
id
result1
{
x
y
z
}
}
}
And there are many classes extending ParentClass and I have different query methods for those concrete classes i.e while firing query I know which concrete objects will be assigned to List result1 . In this case of query; at run time concrete objects of ChildClass are assigned to List<ParentClass>.

**Comment by kaqqao** [comment]
Please use proper [syntax formatting](https://help.github.com/en/articles/creating-and-highlighting-code-blocks#syntax-highlighting) when posting code. It is very difficult to read it otherwise.

GraphQL is strongly typed, similar to Java. And just like you couldn't do `parentClass.getZ()` in Java, you can't do it in GraphQL either. In order to invoke a method from a sub type in Java, you'd have to explicitly down cast the instance: `((Child) parent).getZ()`. Similarly, you have to do a conditional query in GraphQL:
```graphql
{
  myQuery {
    result {
      x
      y
      ... on Child {
        z
      }
    }
}
```

For this to work, the parent type must be mapped as an interface in GraphQL, as there's bo such thing as an abstract class. To map a type as an interface in SPQR, use `@GraphQLInterface(name="Parent", implementationAutoDiscovery=true)`.
`implementationAutoDiscovery` will find the implementing classes and add them to the schema. If you also use the sub classes directly somewhere, you do not need to use `implementationAutoDiscovery`.

**Comment by Rashi-G** [comment]
Thanks a lot for help and this amazing library!
