### ISSUE TITLE
JacksonValueMapper doesn't support Immutables

### ISSUE THREAD

**Issue by arssycro** [leangen/graphql-spqr#245]
Immutables [support](https://immutables.github.io/json.html) Jackson serialization and deserialization using annotations. However, the JacksonValueMapper [limits creating InputFields](https://github.com/leangen/graphql-spqr/blob/c2b847f0edc10000a7f3ee837543cbe264641750/src/main/java/io/leangen/graphql/metadata/strategy/value/jackson/JacksonValueMapper.java#L97) to those that can be directly deserialized. This forces the creation of POJOs for inputs, while Immutables can be used for outputs.

The JacksonValueMapper should support the annotated fields within a deserializable class.

**Comment by kaqqao** [comment]
I'll see what can be done. Since it seems to rely on regular Jackson features, it can be probably be easily supported.
But, in general, it's not reasonable to expect every library under the sun to work out of the box. This is why key interfaces like `InputFieldBuilder ` are made customizable. You could provide your own Immutables-aware implementation.

**Comment by kaqqao** [comment]
Input field mapping rules for abstract types have been greatly relaxed, so Immutables should now work just fine.

See #293 for details.
