### ISSUE TITLE
Multiple Interfaces to implement

### ISSUE THREAD

**Issue by sarbhsinghal** [leangen/graphql-spqr#257]
Hi,  
I have currently started working on SPQR and what issue i am facing is Suppose i have two class annoted with @graphqlInterface,

@GraphqlInterface
class abstract A{}

@GraphqlInterface
class abstract B{}

then, If I have a class with annoted @GraphqlType which needs to implement both above graphql interface, then how to do that because in java we can't extend multiple classes.

@GraphqlType
class C {}

Class C need to implement A & B.

**Comment by kaqqao** [comment]
You can't, normally. But I also fail to see how such a thing would be useful? What object would your resolver method return?

You can force something like this via a custom mapper, say:

```java
@GraphQLInterface(name = "A")
public abstract class A {
    public String a() {return "a";}
}

@GraphQLInterface(name = "B")
public abstract class B {
    public String b() {return "b";}
}

//C must have all the methods declared by both A and B. One way to achieve that is through composition
public class C {

    private final A a;
    private final B b;

    public C(A a, B b) {
        this.a = a;
        this.b = b;
    }

    @GraphQLQuery
    public String a() {return a.a();}

    @GraphQLQuery
    public String b() {return b.b();}
}

public class CustomMapper extends ObjectTypeMapper {

    @Override
    protected List<GraphQLOutputType> getInterfaces(AnnotatedType javaType, List<GraphQLFieldDefinition> fields, BuildContext buildContext, OperationMapper operationMapper) {
        List<GraphQLOutputType> interfaces = super.getInterfaces(javaType, fields, buildContext, operationMapper);
         //Add A and B as interfaces, artificially
        Arrays.asList(A.class, B.class).stream()
                .map(GenericTypeReflector::annotate)
                .filter(buildContext.interfaceStrategy::supports)
                .map(i -> operationMapper.toGraphQLType(i, buildContext))
                .forEach(interfaces::add);
        return interfaces;
    }

    @Override
    public boolean supports(AnnotatedType type) {
        return ClassUtils.isSuperClass(C.class, type);
    }
}
```

Then register the mapper:

```java
generator.withTypeMappers(new CustomMapper());
```

Now, `C` will have `A` and `B` as interfaces in the schema, but again, this is simply not useful. Because if a resolver declares that it returns `A` or `B`, you still can't return an instance of `C`, so there's no point to doing any of this.

You'd have to do a lot more hacking to work around that. But at that level you're simply better off wrapping the whole thing into some custom code specific to your GraphQL API.
