### ISSUE TITLE
@GraphQLInputField ignored where @GraphQLQuery is inspected

### ISSUE THREAD

**Issue by codelizrd** [leangen/graphql-spqr#265]
Hey!

I wonder if this is intended behaviour or an issue. My setup (simplified): 
```
package me.test.model;

class TestObject {
   private String message;

   @GraphQLQuery(name = "message")
   public String getMessage() {
       return this.message;
   }

   @GraphQLInputField(name = "message")
   public String setMessage(String message) {
      this.message = message;
   }
}
```

```
GraphQLSchema schema = new GraphQLSchemaGenerator()
     .withNestedResolverBuilders(
          //Resolve by annotations only
          new AnnotatedResolverBuilder())
     // Only scan this package
     .withBasePackages("me.test.graphql") 
     ...
```

```
package me.test.graphql;

@Service("customerService")
public class MessageService {
    @GraphQLQuery
    List< TestObject> getMessages() {
          ....
    }

    @GraphQLMutation
    void addMessage(@GraphQLArgument(name = "message") TestObject message) {
         ....
    }
}
```

In my setup I expose explicitly everything within the `me.test.graphql` package; referenced objects are exposed by `@AnnotatedResolverBuilder`.

In my schema, I get a `TestObject` declaration which correctly has `message` as a field. The resulting `TestObjectInput` declaration however does not have inputFields.

So, the fields are exposed correctly, but when used as an input argument the schema is incorrect in that it does not discover the `@GraphQLInputField` annotations.

When I move TestObject to the package set by `withBasePackages ` it works (the inputFields are in the schema) but I don't want this; it should remain in `me.test.model` (together with many other related objects, most which should not be exposed by SPQR).

How to fix this?

**Comment by kaqqao** [comment]
The `basePackages` are intended to be the actual base packages of the whole application, not only the packages for the GraphQL stuff. They're there as means to avoid accidentally exposing framework classes or JDK stuff.
As a result, _anything_ (well, almost anything) outside of `basePackages` will be ignored. The line removing the input field is [this one](https://github.com/leangen/graphql-spqr/blob/graphql-spqr-v0.9.9/src/main/java/io/leangen/graphql/metadata/strategy/DefaultInclusionStrategy.java#L34). Because the method is declared by a class outside of the base packages, it gets ignored. So in your case, the base package should be `me.test`.

But I'm confused by your intention here. Why choose a base package and then intentionally put something (that should be exposed) outside of it? There's a `graphql` base package but then `@GraphQL` annotated stuff outside of it that should be exposed? Seems convoluted for no reason...

Anyway, you can override `InclusionStrategy` but I wouldn't recommned doing that as it will just get confusing. Instead, I'd suggest simply chaging the base package to `me.test`, becaue you're already only exposing explicitly annotated elements only (by the exclusive use of `AnnotatedResolverBuilder`), so there's no risk of something leaking accidentally anyway.

**Comment by codelizrd** [comment]
Ah, I misunderstood the concept then. I added the other package to the list of basePackages and it works indeed.

It was a bit confusing that `@GraphQLQuery` worked and `@GraphQLInputField` didn't.

Sorry!

**Comment by kaqqao** [comment]
> It was a bit confusing that @GraphQLQuery worked and @GraphQLInputField didn't.

You're right... it _is_ confusing. Output fields will only get fieltered out according to base packages when their inherited, while the fields directly on a class will always be accepted. I'm not exactly sure wht input fields don;'t act the same way... I'll see if I can make it more consistent.
