### ISSUE TITLE
Add description to @GraphQLId annotation

### ISSUE THREAD

**Issue by darrikonn** [leangen/graphql-spqr#266]
## What?
`@GraphQLId` can be represented as a `@GraphQLArgument`, is there any reason why a description is not present in the `GraphQLId` annotation?

## Why?
This would allow us to skip adding `@GraphQLArgument` in order to provide a description, if `@GraphQLId` is already present.

## How?
```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.PARAMETER, ElementType.TYPE_USE, ElementType.FIELD, ElementType.TYPE})
public @interface GraphQLId {
    String RELAY_ID_FIELD_NAME = "id"; //The name of the ID field, as defined by the Node interface

    String description() default "";
    
    boolean relayId() default false;
}
```

**Comment by kaqqao** [comment]
`@GraphQLId` is really a type-level annotation, and can appear anywhere e.g. `List<@GraphQLId String>`, not only on an argument level.  For this reason, it makes no sens to add a description argument directly to the `@GraphQLId`. It would enable you to write carzy stuff like:

```java
Map<@GraphQLId(description = "Something" String, @GraphQLId(description = "Something else") Long)>
```

The only reason the annotation is also applicable on `ElementType.PARAMETER` is to partially* work around the issue of JSON libraries having no support for type-level annotations. By placing the annotation directly on the argument, SPQR has a chance to process the value before/after the JSON library, so it can sometimes* apply the needed logic itself.

*Saying _partailly_ and _sometimes_ because it only works when the argument _is_ itself an ID, does not work when the argument _contains_ the ID.

**Comment by darrikonn** [comment]
Ah, aight! Thanks for the explanation 👍!

Closing this!

**Comment by kaqqao** [comment]
No worries :)

One thing I'm potentially interested in supporting is Spring style meta-annotations, so that you can make your own annotation to group multiple others.
Of course, you can already achieve any custom mapping/argument injection (using custom annotations with custom semantics) if you're willing to get your hands a little dirty with `ResolverArgumentBuilder` and/or `ArgumentInjector`.

**Comment by darrikonn** [comment]
That sounds cool!

Before I used graphql-spqr, I created a resolver annotation (for 1-1 mapping) to reduce the amount of code needed.
I don't like the idea of making changes on the db entity layer regarding graphql stuff. I rather want to create my own DTOs and keep the graphql logic there. So entity data return from the ORM or objects from elastic search will be mapped to graphql types. The resolver that I created was something like this:
```java
@Resolver(source = "description")
private String desc;
```
That way, the resolver would know to use the `getDescription` getter of the entity class and map it to `desc`. No extra getter/setter needed there. The default would map to the exact same field, i.e.
```java
@Resolver
private String description;
```

If a more complicated resolver was needed, I would specify where to calculate that logic:
```
java
@Resolver("descriptionResolver")
private String description;

public String descriptionResolver() {
    ...
}
```
