### ISSUE TITLE
Annotated methods returing a String are showing as a collision with unannotated methods returning a String

### ISSUE THREAD

**Issue by erindru** [leangen/graphql-spqr#284]
I am using graphql-spqr in a Spring Boot app via the Spring Boot Starter. The Spring Boot Starter currently references 0.9.9 so I included 0.10.0 in my `build.gradle` to see if this issue was fixed, but it still persisted in 0.10.0.

Anyway, I have a bunch of entity classes, eg:

```java
import javax.validation.constraints.NotBlank;

public class Entity1 {
    public String getField() { return "field value"; }
    public int getOtherField() { return 1; }
}

public class Entity2 {
  @NotBlank
  public String getValidatedField() { return "value"; }
}
```

These are used in a service annotated with `@GraphQLApi`, eg:

```java
@GraphQLApi
public class EntityService {

  @GraphQLQuery(name = "entity1")
  public Entity1 getEntity1() {
    return new Entity1();
  }

 @GraphQLQuery(name = "entity2")
  public Entity2 getEntity2() {
    return new Entity2();
  }
}
```

This all works great. However, the following warning is printed to the console on application start:

```
2019-07-05 13:20:15.910  WARN 31447 --- [           main] i.l.graphql.generator.OperationMapper    : Potential type name collision detected: 'String' bound to multiple types: java.lang.String (loaded by the bootstrap class loader) and @javax.validation.constraints.NotBlank(message="{javax.validation.constraints.NotBlank.message}", payload={}, groups={}) java.lang.String (loaded by the bootstrap class loader). Assign unique names using the appropriate annotations or override the TypeInfoGenerator. For details and solutions see https://github.com/leangen/graphql-spqr/wiki/Errors#non-unique-type-name. If this warning is a false positive, please report it: https://github.com/leangen/graphql-spqr/issues.
```

I spent some time attempting to debug why this occurs, but with no success. The closest I could figure was that "java.lang.String with an annotation" and "java.lang.String" both match the "String" GraphQL type, but when the Validator calls `isMappingAllowed`, the comparison fails because it considers "java.lang.String with an annotation" and "java.lang.String" to be different.

Is there a way to ignore annotations that you have no control over and cannot add`@GraphQLIgnore` to? Or is this another case to consider for Issue #232

**Comment by kaqqao** [comment]
Your assessment is spot on - a type with an annotation and a type without are considered as different (because they might as well be), but this is highly problematic logic... And yes, cases like this are exactly the reason #232 is open... On one hand, I'm want to ax the check because it's so unreliable, on another, it might prevent some genuinely tricky situations.

**Comment by kaqqao** [comment]
For the meantime, you could make a comparator like this:

```java
public class IgnoredAnnotationsComparator implements Comparator<AnnotatedType> {

    private final Set<Class<? extends Annotation>> ignoredAnnotations;

    public IgnoredAnnotationsComparator(Class<? extends Annotation>... ignoredAnnotations) {
        Set<Class<? extends Annotation>> ann = new HashSet<>();
        Collections.addAll(ann, ignoredAnnotations);
        this.ignoredAnnotations = Collections.unmodifiableSet(ann);
    }

    @Override
    public int compare(AnnotatedType o1, AnnotatedType o2) {
        Class<?> r1 = ClassUtils.getRawType(o1.getType());
        Class<?> r2 = ClassUtils.getRawType(o2.getType());
        return (r1.equals(r2) && annotationsMatch(o1, o2)) ? 0 : -1;
    }

    private boolean annotationsMatch(AnnotatedType o1, AnnotatedType o2) {
        Set<? extends Class<? extends Annotation>> a1 = Arrays.stream(o1.getAnnotations())
                .map(Annotation::annotationType)
                .collect(Collectors.toSet());
        Set<? extends Class<? extends Annotation>> a2 = Arrays.stream(o2.getAnnotations())
                .map(Annotation::annotationType)
                .collect(Collectors.toSet());

        return a1.stream().noneMatch(ann -> !a2.contains(ann) && !ignoredAnnotations.contains(ann))
                && a2.stream().noneMatch(ann -> !a1.contains(ann) && !ignoredAnnotations.contains(ann));
    }
}
```

When comparing types, it will check that they only differ in ignored annotations. You can then register it via:

```java
generator.withTypeComparator(new IgnoredAnnotationsComparator(NotBlank.class))
```

This is of course way too cumbersome... and will likely change soon... but it is something you can do if you want to.

**Comment by seanf** [comment]
Thanks for the workaround @kaqqao. I was getting an almost completely unreadable error message (more binary than text) in my Scala project. Apparently the `toString` method for machine-generated `scala.reflect.ScalaSignature` annotations includes a big chunk of binary data. 

Using `.withTypeComparator(new IgnoredAnnotationsComparator(classOf[scala.reflect.ScalaSignature]))` did the trick.

**Comment by kaqqao** [comment]
@seanf Yeah, Scala crams rather scary stuff into annotations 😨
Btw, it's rather interesting to hear someone is finding SPQR useful with Scala 😁 What's the experience like? Any significant friction?

@erindru @seanf `IgnoredAnnotationsTypeComparator` is now a part of the API, and an instance is set up by default to ignore all annotations except the ones from the `io.leangen` package. This can be easily overridden via `GraphQLSchemaGenerator#withTypeComparators`.

**Comment by austinarbor** [comment]
Is this only fixed for `@NonNull` annotations? I am having the same false alarms with other `javax.validation` annotations such as `@Size` and `Min` etc

**Comment by kaqqao** [comment]
@austinarbor  As I said, it [ignores _all_ annotations except the ones from the `io.leangen` package](https://github.com/leangen/graphql-spqr/blob/906e816f0fb2cdc46335e6f1048f231be6b1045c/src/main/java/io/leangen/graphql/GraphQLSchemaGenerator.java#L953), by default.

For customizations, see [`SynonymBaseTypeComparator`](https://github.com/leangen/graphql-spqr/blob/906e816f0fb2cdc46335e6f1048f231be6b1045c/src/main/java/io/leangen/graphql/generator/mapping/IgnoredAnnotationsTypeComparator.java) and [`IgnoredAnnotationsTypeComparator`](https://github.com/leangen/graphql-spqr/blob/906e816f0fb2cdc46335e6f1048f231be6b1045c/src/main/java/io/leangen/graphql/generator/mapping/SynonymBaseTypeComparator.java) for some convenient comparator implementations provided out of the box.

**Comment by seanf** [comment]
@kaqqao Re: Scala, from memory (so far, still in progress):

In terms of basic Scala compatibility, there were a couple of `with` methods where Scala couldn't infer the right overload to call, but so far I just found a different method to call. 

Most of the other problems are to do with supporting Scala's native collection types for more idiomatic code, but coming up with **any** sort of general solution for nullable vs non-nullable types is proving very difficult.

I've had to create adapters/mappers for Scala `Option` and Scala `Iterable` by borrowing from `OptionalAdapter` and `ListMapper`. Also graphql-java has a method `ExecutionStrategy.toIterable` which doesn't understand Scala's `Iterable`, so I had to work out which `ExecutionStrategy` to subclass.  It was hard to find the right place to pass in my ScalaOptionAdapter, my ScalaIterableMapper and my `ExecutionStrategy`, because some of them were a few levels down from the top. I'm going from memory here, so some of those problems may have been with graphql-java-servlet.

A big difficulty is the fact that Scala can't annotate a type parameter the way Java can, eg `List<@GraphQLNonNull String>` - https://stackoverflow.com/questions/38833827/how-to-annotate-a-type-parameter-in-scala  The alternative, more idiomatic typing in Scala would be `List[Option[String]]` , but arranging for anything wrapped in Option to become nullable in GraphQL, but anything not wrapped in option to become non-nullable, is proving very difficult. 

The [existing mapping of `java.util.Optional`](https://github.com/leangen/graphql-spqr/issues/307) is a bit of a problem if applied to Scala `Option`, because if you use Scala's `Option` in your types you probably don't want anything to be nullable, at least by default. The idea of a method with an `Option` parameter receiving a null at runtime is pretty unpleasant. 

I've been trying to use a `SchemaTransformer` to make `Option[X]` in Scala map to nullable `X` in the schema, and make `X` in Scala map to non-nullable `X!` in the schema, but so far it all falls apart if you're dealing with more complex types, where you might have optionality at some but not all points. Such as `List[Option[String]]`, `List[String]`, `Option[List[String]]`, `Option[List[Option[String]]]` which should map to `[String]!`, `[String!]!`, `[String!]`, `[String]` respectively, I think.

So far I haven't been able to create a `SchemaTransformer` which can handle those cases. Especially because GraphQL-Java represents nullable by the absence of the GraphQLNonNull wrapper object, and non-nullable by its presence, which is the opposite of `java.util.Optional` and Scala `Option`. Even the shape of the trees is different, which makes it hard to come up with a recursive algorithm to modify the GraphQLInput/OutputType based on the corresponding Java Type in the tree.

**Comment by seanf** [comment]
An update on the subject of SPQR with Scala:

I got my `NonNullSchemaTransformer` to work by first converting the Java `Type`s into another tree structure (I called it `TypeInfo`) which always wraps nodes in Required or Optional to help with the tree shape problem above. In actual fact, I have five node types(!): ListTypeInfo, RequiredNonLeafTypeInfo, OptionalNonLeafTypeInfo, RequiredLeafTypeInfo, OptionalLeafTypeInfo.

Then `SchemaTransformer.transformArgument` and `SchemaTransformer.transformField` recursively descend into the `GraphQLType` (from `GraphQLArgument.getType` or `GraphQLFieldDefinition.getType`) together with the corresponding `TypeInfo` (converted from `GraphQLArgument.getBaseType.getType` or `Operation.getJavaType.getType`) at each level of recursion. It's certainly not pretty, but it seems to work.

Finally (I hope) I had to create an `ArgumentInjector` to pre-empt `InputValueDeserializer`, ensuring that I never receive a `null` for an `Option` parameter. Might have to revisit that if we ever need to distinguish between `null` and `undefined` as the schema evolves.

In summary:

- I'm pleased with how configurable SPQR is, given that I've needed to plug in a `TypeMapper`, a `TypeAdapter`, a `ResolverInterceptor`, a `SchemaTransformer` and an `ArgumentInjector`.
- GraphQL-Java could use some pluggability when it comes to handling `Iterable`s, given that it assumes all GraphQL lists are either native arrays or `java.lang.Iterable`s.
- `ResolverInterceptor` is a lifesaver, along with the example `AuthInterceptor` in `InterceptorTest`. Thanks @kaqqao !
- My `SchemaTransformer` worries me a bit. It doesn't handle GraphQL unions or Scala `Map`s yet (don't need them yet) but it's already a fair amount of code, so it could be a maintenance problem. 
- The other mappers, adapters and injectors were all nice and straightforward (other than a Scala type inference surprise when calling `ResolutionEnvironment.convertOutput` from my ScalaOptionTypeAdapter).
