### ISSUE TITLE
Subscriptions not working with withOperationsFromSingleton

### ISSUE THREAD

**Issue by dwardrian** [leangen/graphql-spqr#289]
Perhaps not an issue - I'm a bit of a newbie so forgive my ignorance :)

I'm using the new built in subscriptions with Apollo (@GraphQLSubscription). It all works beautifully, unless I add .withOperationsFromSingleton(<service>) to the GraphQLSchemaGenerator. I had originally thought the subscriptions stuff was not working at all but since realised it works without that config

Any pointers? Thanks

**Comment by kaqqao** [comment]
Can you exemplify what you mean? `withOperationsFromSingleton` is pretty much the only way to even get a schema, so if subscriptions wouldn't work with that, they wouldn't work ever. In fact, pretty much nothing would work ever... So it has to be more specific than that. That's why I'm asking for an example.

**Comment by kaqqao** [comment]
Any news?

**Comment by kaqqao** [comment]
Closing this one since there was no response in a long while... Feel free to reopen if you still need help.
