### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by luizpaulofranz** [leangen/graphql-spqr#294]
Hi there, I'm using SQPR on my API, and I wish to throw Exceptions when needed, so as it is a simple `@RestController` resource `@PostMapping(value = "/graphql" ...)`, I'm trying to use the Exception Handling due by Spring a `@ControllerAdvice` annoted ExceptionHandler class where I catch my custom Exceptions, but when I throw my new Exception It is always catched by **OperationExecutor** and my ExceptionHandler never catches it. How could I handle my own exceptions in an external ExceptionHandler and sends back a json to graphQl direct from there? See my codes:

My Service:
```
@GraphQLQuery(name = "parametros")
	public List<Parametro> getParametros(@GraphQLArgument(name = "processo") Integer processo, @GraphQLRootContext HttpServletRequest context) throws CronosUnauthorizedException {
	if (this.checkCondition()) {
		throw new CronosUnauthorizedException();
	}	
	return parametroRepository.findByProcesso_idProcesso(processo);
}
```
And my ExceptionHandler:

```
@ControllerAdvice
public class ExceptionHandler extends ResponseEntityExceptionHandler {

@org.springframework.web.bind.annotation.ExceptionHandler(CronosUnauthorizedException.class)
	public ResponseEntity<Object> handleUnauthorizedException(Exception e,
			HttpServletRequest request) {
		
		DetalheErro erro = new DetalheErro();
		erro.setStatus(401l);
		erro.setTitulo(e.getMessage());		
		return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(erro);
	}
}
```

**Comment by zotona** [comment]
You could use AOP wrapper, like this:
```
@Aspect
@Component
public class GraphQlExceptionWrapAop {

    @Pointcut("@annotation(io.leangen.graphql.annotations.GraphQLMutation)")
    private void graphqlMutation() {}

    @Pointcut("@annotation(io.leangen.graphql.annotations.GraphQLQuery)")
    private void graphqlQuery() {}

    @Around("graphqlMutation() || graphqlQuery()")
    public Object wrapException(ProceedingJoinPoint jp) {
        try {
            return jp.proceed();
        } catch (Throwable throwable) {
            throw new GraphQLException(throwable);
        }
    }

}

```

**Comment by kaqqao** [comment]
You're forgetting that it's completely normal in GraphQL to have a partial result and multiple potential errors in the response. The resolution does not stop on the first exception (unless it's an `AbortExecutionException`). This is due to GraphQL's ad-hoc nature, so REST style exception handling doesn't map well.

You already have access to all the collected exceptions in `ExecutionResult`. `DataFetchingException` will have the original exception inside. Inspect the errors you receive `ExecutionResult` and decide what to do with them.

But, you should note it's highly unusual for a GraphQL endpoint to return HTTP errors unless something is wrong with the engine itself. A (partial) result with errors is still normally with 200 status code.

Also note that `OperationExecutor` only catches exceptions to unwrap reflection-related exceptions, and then immediately re-throws. So `OperationExecutor` is not causing you any trouble.
It is graphql-java's `DataFetcherExceptionHandler` that catches the exceptions (as it should). You can change the handler used there by overriding it in the `ExecutionStrategy` that you can provide when creating `GraphQL` object.

**Comment by kaqqao** [comment]
One more thing, you can also customize exception handling to a degree by providing a `ResolverInterceptor` that can return a custom `DataFetchingResult` in case of an error (or always, for that matter).
This will not do what you want (bubble up the exception to the controller level) but gives you a great degree of control over what reaches graphql-java. `ResolverExecutor` is basically an around-invoke AOP advice.

I'm on my phone now and can't provide a code sample, but search around a bit of you're interested, there's a few examples I've posted before (I think I also posted a detailed one on StackOverflow the other day).

**Comment by kaqqao** [comment]
Closing this as it seems addressed and there was no feedback for a very long time. Please reopen if you need more help.
