### ISSUE TITLE
Extensions Support in @GraphQLQuery and @GraphQLMutation

### ISSUE THREAD

**Issue by entimaniac** [leangen/graphql-spqr#315]
I'd like a convenient way to manipulate the extensions map in a GraphQL response. I'd love if I can add something like a GraphQLExtensions object in the argument list of a @GraphQLQuery method, adding data to this object would show up the response. I'm imagining using it the same way a SpringBoot controller can include and manipulate a Model. 

While implementing paging, I'm faced with how I'd like to return paging-specific data. Most consumers expect not only a list of objects, but also how many total results there are and whether the returned page is first or last etc. Ideally I'd have a GraphQLQuery that accepts a page and pageSize that then returns a list of the objects desired and then some paging metadata. I could return a Page object that holds this information with the list of objects inside a `content` field but what I think really feels good to me is adding in metadata in the extensions map provided by the GraphQL specification.

**Comment by kaqqao** [comment]
There's a few things to note here. graphql-java itself offers no convenient way to add extensions to the `ExecutionResult`. There is [a PR that attempts to add such a feature](https://github.com/graphql-java/graphql-java/pull/1482), but no clue where that goes.

What you could do is register an instrumentation that enhances the `ExecutionResult` with the data collected during execution. This is what the built-in `TracingInstrumentation` does when it collects the tracing info for each resolved field and adds that to the extensions. You can look into that class for inspiration and develop something similar if you decide to take that route.

With all that said, I'd highly recommend you do _not_ do that and adopt [Relay's Connection spec](https://relay.dev/docs/en/v6.0.0/graphql-server-specification) instead, as it already solves that problem and is standard solution that most clients know how to consume out of the box.

If you make a method return `io.leangen.graphql.execution.relay.Page<Something>`, SPQR will map that as a Relay connection. You can either implement the `Page` interface yourself, or use the provided `PageFactory` to create simple offset-based pages (see the tests for usage ideas) or ping in Gitter if you need help. You can also directly use `Connection<Edge<N>>` if you need to add more fields to the connection.

If you're using Spring Data, I'm working on a mapper/converter that translates Spring Data's `Page`s to Relay Connections or optionally maps them directly, for a more simple paging solution (that still has all the features you're after).

Since GraphQL puts a full type-system at your disposal, there's no reason to side-load paging data.

**Comment by entimaniac** [comment]
Thanks for the response! I suspected that support was lacking since I couldn't find much documentation for it and anything I did find advised jumping through `Instrumentation` hoops as well. I do hope for extension support at some level in the near future. 

 I've seen cursor based pagination model mentioned in graphql circles a lot but it seems like a lot of overhead for pagination and corrupts my response DTOs with pagination fields. For now I've approached pagination by returning a page object with my list of data inside of it. It still doesn't feel ideal but we'll survive. 

I look forward to seeing your Spring Data mappers, best of luck!
