### ISSUE TITLE
Replace @GraphQLQuery by for Type generation

### ISSUE THREAD

**Issue by aoudiamoncef** [leangen/graphql-spqr#316]
Hi @kaqqao,

@GraphQLType @GraphQLModel could be better.
Thanks

**Comment by kaqqao** [comment]
Care to elaborate?

**Comment by Sparow199** [comment]
```java
@GraphQLQuery(name = "id") public Long getId() { return id; }
```

I think that this syntax is a little bit confusing, it could be more intuitive like this:

```java
@GraphQLField||Model||Type(name = "id") public Long getId() { return id; }
```

**Comment by kaqqao** [comment]
Field, type and model are very different concepts and are not interchangeable. The only one making sense in this context would be a _field_. Originally, SPQR did distinguish between a query (`@GraphQLQuery`) and a field (`@GraphQLField`), but this creates a false dichotomy as all GraphQL operations (queries, mutations and subscriptions) _are_ fields. And nested fields _are_ nested queries (the other operations can't be nested). Additionally, since in GraphQL a query at any level can accept parameters, the analogy to what a field is in Java terms falls apart. So it's better to see any exposed method for what it is - a _query_ (with exactly the same semantics as the top level query). And the current set of annotations, I believe, expresses that correctly.

**Comment by aoudiamoncef** [comment]
Thanks for your reply.
I always searched for an example for parametersed fragment in GraphQL Java,
have you an example of this usecase even if it's not with SPQR ?

**Comment by kaqqao** [comment]
You can freely use variables inside fragments. See an example e.g. [here](https://graphql.org/learn/queries/#using-variables-inside-fragments).

Fragments are sent by client, as a part of the query. SPQR is used to generate a schema and implement a server, so it has nothing to do with fragments.
