### ISSUE TITLE
@GraphQLNonNull Not Respected on Sub Classes

### ISSUE THREAD

**Issue by austinarbor** [leangen/graphql-spqr#336]
If I have two classes
```java
public class A {
  protected Integer id;
 //getters, setters, other fields
}
```
and
```java
public class B extends A {
 @GraphQLNonNull
  public void setId(Integer id) {
    this.id = id;
  }
}
```

The `@GraphQLNonNull` annotation on the inherited class is not respected in the generated schema

**Comment by kaqqao** [comment]
Not sure what you're expecting to happen here. The example is syntactically incorrect (it's trying to annotated `void` which does not compile), and I can only assume you meant to make the `id` non-null.
I.e.

```java
public class B extends A {
  public void setId(@GraphQLNonNull Integer id) {
    this.id = id;
  }
}
```

Since the annotation is on the setter, it applies to input type only. I.e. if `B` is used as an input it will be mapped as:

```graphql
input BInput {
  id: Int!
}
```

which is exactly as intended.

If you want the `id` field to be non-null in the output type, you should use `@GraphQLNonNull` at getter level.

E.g.

```java
public class B extends A {

        @Override
        public @GraphQLNonNull Integer getId() {
            return super.getId();
        }

        @Override
        public void setId(@GraphQLNonNull Integer id) {
            this.id = id;
        }
}
```

Which produces

```graphql
type B {
  id: Int!
}
```

as expected.
