### ISSUE TITLE
Using @JsonTypeInfo annotated entities

### ISSUE THREAD

**Issue by cristian-spiescu** [leangen/graphql-spqr#353]
Hello!

Until now, the migration of our legacy app -> GraphQL + SPQR went well; until we started dealing w/ classes annotated w/ `@JsonTypeInfo` (and some w/ `@JsonSubTypes`).

E.g.:
```java
@JsonTypeInfo(use=JsonTypeInfo.Id.NAME, include=As.PROPERTY, property="objectType")
@JsonSubTypes({
      @JsonSubTypes.Type(value=Company.class, name="Company"),
      @JsonSubTypes.Type(value=Logistics.class, name="Logistics"),
      @JsonSubTypes.Type(value=Person.class, name="Person")
  })
public class Resource {
// ...

@JsonTypeName("Company")
public class Company { 
// ...
```

A query that outputs a `Company` works OK. But for a mutation, Jackson throws an error, complaining that it cannot find field `objectType` (in the JSON string that came from the client):

```
...
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class myPackage.Company]: missing type id property 'objectType' (for POJO property 'company')
...
```

**Question 1:** What would be the current approach in this solution? I experimented a temporary solution w/ [this approach](https://stackoverflow.com/questions/56797172/json-to-object-deserialization-issue-in-graphql-spqr), i.e. creating:

```java
@JsonTypeName("Company")
public class Company { 
    public String objectType = "Company";
```
But I'm thinking that a more general approach may be applied, w/o manually modifying tenths of files.

**Question 2:** I think that `objectType` needs to appear in the generated schema, right? Because otherwise there is no way for the client to obtain the information in this field. So probably an "enricher" is needed, that would parse the Jackson annotations and try to mimic the "manual" approach above?

**Question 3:** Does the SPQR code already scans for Jackson annotations, so that we can somehow hook into this process?

**Question 4:** On deserialization nothing seems to be needed, right?

Thanks a lot in advance!
Best regards,
Cristian.

**Comment by kaqqao** [comment]
Have you figured this out? In general, polymorphic or otherwise strange JSON is difficult with GraphQL, as you're not actually dealing with JSON _at all_, but with GraphQL input, which only accidentally _looks_ like JSON, but has its own **type system** and rules. In fact, it's an implementation detail that Jackson is even used internally for translation. It would be possible to use something like MapStruct, as raw GraphQL input are effectively maps, not JSON strings (even in JavaScript).

Still, SPQR _does_ work with polymorphic inputs, BUT it really wants to be left alone, without too many Jackson configurations. While SPQR tries to not get in the way of basic Jackson functionality, I hope you understand that dealing with every possible Jackson setup is as big a project as Jackson itself.

For your situation, if you didn't something like this (note the lack of `@JsonTypeInfo` etc):

```java
    public abstract static class Resource {
        //Some GraphQL-exposed fields/methods must exist here
    }

    //All possible inputs types must have a common ancestor, otherwise there'd simply be no way to map anything
    //without some vary heavy case-specific customizations
    public class Company extends Resource {
        ...
    }

    public static class Logistics extends Resource {
        ...
    }

    public static class Person extends Resource {
        ...
    }

    public class ResourceService {
        
        @GraphQLQuery
        public Resource test(Resource in) {
            return in;
        }
    }
```

You could instruct SPQR to deal with this situation:

```java
GraphQLSchema schema = new GraphQLSchemaGenerator()
                .withAbstractInputTypeResolution() //This is the magic line
                .withOperationsFromSingleton(new ResourceService())
                .generate();
```

This would result in `ResourceInput` type having a discriminator field called `_type_` that is an enum with 3 possible values: `Company`, `Logistics` and `Person` and Jackson would be automatically configured to handle this.

You could still keep `@JsonTypeInfo`,` @JsonSubTypes` etc in place if needed for other scenarios, SPQR would just be unaware of them.

It _is_ possible to setup SPQR to support all these too, but it's a large effort involving customizing a both input and output mappers. In the future I might look into building this in, but it's a lot of work for a limited pay off...

**Comment by kaqqao** [comment]
Oh, if you decide you want to go down the rabbit hole, ping me here and I'll guide you in the right direction. It would be cool if you ended up making it generic enough to contribute it to SPQR.

**Comment by kaqqao** [comment]
Ok, now this got me to start experimenting... and it might be easier than I though. Lemme get back to you in a couple of days 🤓

**Comment by kaqqao** [comment]
While SPQR does cooperate with Jackson pretty well, this setup required significant tinkering. I've now made some changes that improve the situation.

For example, this should work out-of-the-box now:

```java
@JsonTypeInfo(use=JsonTypeInfo.Id.NAME, include=As.PROPERTY, property="objectType")
@JsonSubTypes({
      @JsonSubTypes.Type(value=Company.class, name="Company"),
      @JsonSubTypes.Type(value=Logistics.class, name="Logistics"),
      @JsonSubTypes.Type(value=Person.class, name="Person")
  })
//Note that the root type must be an abstract class or an interface
public abstract class Resource { ... }

public class Company extends Resource { ... }
```

If `Resource` is used as input, it would get mapped as `ResourceInput` with an extra field called `objectType` that is of `GraphQLEnum` type with `Company`, `Logistics` and `Person` as possible values of the enum. Deserialization should work as expected.
Note that still only the fields from `Resource` class itself would be mapped. Mapping also the fields from subtypes is much harder, as that would have to include dealing with conflicting fields (same name but different type in different subtypes) and configuring Jackson to ignore unknown fields. I'll consider making this easier to implement somehow, but the some custom setup would definitely still be required.

**Comment by brettcooper** [comment]
Is there a reason the default property name "@type" doesn't work?

```
@JsonTypeInfo(use = Id.NAME)
@JsonSubTypes({@Type(value = JsonEntityTransformerConfiguration.class, name = "json"),
        @Type(value = CouponRequestTransformerConfiguration.class, name = "coupon-json")})
public abstract class EntityTransformerConfiguration {

    private EntityType entityType;

    public EntityType getEntityType() {
        return entityType;
    }

    public void setEntityType(EntityType entityType) {
        this.entityType = entityType;
    }
}
```
org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'graphQLSchema' threw exception; nested exception is graphql.AssertException: Name must be non-null, non-empty and match [_A-Za-z][_0-9A-Za-z]* - was '@type'

**Comment by kaqqao** [comment]
Well... yes, and it's in the exception message 🙃
It violates the GraphQL spec on field names.

**Comment by brettcooper** [comment]
Ok, I didn't realize it is part of the GraphQL spec.  Thanks for the quick response and clarification!  Bummer, we are using the default property "@type" in a few different places and changing it is going to require some work.
