### ISSUE TITLE
Inheriting fields from class are not visible in the generated schema

### ISSUE THREAD

**Issue by labamba63** [leangen/graphql-spqr#399]
Hi! 

I changed the version from 0.9.9 to 0.11.2 and now when generating the schema, inherited fields in the schema do not appear to me. Does anyone know how it's done now?

Regards.

**Comment by labamba63** [comment]
Adding a package is the solution.
GraphQLSchemaGenerator() .withBasePackages(...)

**Comment by kaqqao** [comment]
Just curious, did you not have packages configured before (in 0.9.9)? Because I'd expect you had problems there as well.
In general, if an output field isn't appearing, and you expect it to, place break points in `DefaultInclusionStrategy#includeOperation` and `PublicResolverBuilder#isPackageAcceptable`. Those two are the only places where output fields get filtered.
Other elements (like input fields) also get filtered by `(Default)InclusionStrategy`.
