### ISSUE TITLE
Question regarging custom errors implementation.

### ISSUE THREAD

**Issue by thelesteanu** [leangen/graphql-spqr#40]
Is it possible to add GraphQLErrors based on business logic? 

Eg: an error for each invalid field. (like email invalid or username not available). I was able to show a single Error only by throwing a new GraphQLException.

I'm interested in something like this: 
`{
  "errors": [
    {
      "code": 2222,
      "field": "username",
      "message": "username_not_available",
      "locations": null,
      "errorType": "DataFetchingException"
    },
    {
      "code": 1111,
      "field": "pass",
      "message": "password_is_weak",
      "locations": null,
      "errorType": "DataFetchingException"
    }
  ],
  "data": null,
  "extensions": null
}`

**Comment by kaqqao** [comment]
Sorry for a late response.
There's nothing in SPQR to support this use case, but it should be doable using the regular graphql-java mechanisms. I think you'd just need to implement your own [`DataFetcherExceptionHandler`](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/DataFetcherExceptionHandler.java) that would unroll an exception into multiple `GraphQLError`s. Take a look at [`SimpleDataFetcherExceptionHandler`](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/SimpleDataFetcherExceptionHandler.java). You need to do something similar but adding multiple errors instead of one.

Once you implement the exception handler, add it to the execution strategy via the constructor.

**Comment by thelesteanu** [comment]
Hello @kaqqao .

Thanks for the suggestions. They work as expected. 
Thanks again for this awesome library.

This issue can be closed now :+1:

**Comment by kaqqao** [comment]
Good to hear! Cheers 😊

**Comment by tudorpavel** [comment]
Somehow related to this, how could we configure the `errors` to return `null` instead of `[]`?

We are using [apollo-client](https://github.com/apollographql/apollo-client) and for mutations which are successful we end up in the `error` callback because `errors` is non-null.

bad:
```
{
  "data": {
    "something": true
  },
  "errors": [],
  "extensions": null
}
```

good1:
```
{
  "data": {
    "something": true
  },
  "errors": null,
  "extensions": null
}
```

good2:
```
{
  "data": {
    "something": true
  }
}
```
