### ISSUE TITLE
getting java.lang.NoSuchMethodError: graphql.schema.GraphQLType.getName()Ljava/lang/String;

### ISSUE THREAD

**Issue by ravibegari** [leangen/graphql-spqr#419]
Detailed message:
Error: Error loading a referenced type: java.lang.NoSuchMethodError: graphql.schema.GraphQLType.getName()Ljava/lang/String;
Trace: 
	at parsing io.leangen.graphql.generator.TypeCache.<init>(TypeCache.java:19)
Call path from entry point to io.leangen.graphql.generator.TypeCache.<init>(Collection): 
	at io.leangen.graphql.generator.TypeCache.<init>(TypeCache.java:18)
	at io.leangen.graphql.generator.BuildContext.<init>(BuildContext.java:106)
	at io.leangen.graphql.GraphQLSchemaGenerator.generate(GraphQLSchemaGenerator.java:992)

Dependencies are **implementation  'com.graphql-java:graphql-java:17.3'**
implementation 'io.leangen.graphql:spqr:0.10.1'

![image](https://user-images.githubusercontent.com/41550916/157496025-ed431298-9585-4177-9cb8-08e7ce417ba4.png)

**Comment by ravibegari** [comment]
HI Team, I am getting the above error, it will be great if you can help me

**Comment by ravibegari** [comment]
is there any way to use graphqlSchemaGenerator+DataFetchers in AWS serverless applications
?

**Comment by kaqqao** [comment]
`NoSuchMethodError` can only mean one thing: you're running against an incompatible version of graphql-java. SPQR can only run against the graphql-java version it declares as a dependency. If you override underlying library versions, you;re asking for trouble. Dependency management exists for a reason.

**Comment by sgrannan** [comment]
I feel like the mysterious and ambiguous errors like `NoClassDefFound` or `NoSuchMethodError` shouldn't be the expected behavior whenever there is a version mismatch. When creating libraries we always try to be as succinct as possible with our exception handling. Is there not a better way of handling the exception when things start to autowire up?

You definitely could benefit by informing the user better that they are using a incompatible library. For what its worth, we decided not to use GraphQL SPQR anyway for lack of support/adoption of this particular library back in 2022.
