### ISSUE TITLE
DefaultValue can't be converted when passed as separate values

### ISSUE THREAD

**Issue by lindaandersson** [leangen/graphql-spqr#467]
I am trying to upgrade from 0.11 to 0.12 and I ran into an issue related to DefaultValues. 

My query used to be defined like this: 

```
class Pagination {
  private Integer limit = 10;
  private Integer offset = 0;
}

@GraphQLQuery(name = "items")
  public CompletableFuture<List<Item>> items(
      @GraphQLArgument(
              name = "pagination",
              description = "Pagination of results.",
              defaultValue = "{}")
          final Pagination pagination) { 
// return paginated list of items 
}
```

This used to give me the following schema where the default values were presens. 
```
input PaginationInput {
  limit: Int
  offset: Int
}
type Query {
 items(
    pagination: PaginationInput = {limit : 10, offset : 0}
  ): [Item]
}
```

With the new version I had to explicitly say how the default object should look, otherwise it would not show up in the schema. 
So now I define it like this:
```
@GraphQLQuery(name = "items")
  public CompletableFuture<List<Item>> items(
      @GraphQLArgument(
              name = "pagination",
              description = "Pagination of results.",
              defaultValue = "{\"limit\":10, \"offset\":0}")
          final Pagination pagination) { 
// return paginated list of items 
}
```

The issue is that when I make a query towards a GraphQLQuery with a GraphQLArgument that has defaultValue set like this, and if I write my query like this (which used to work, and should work), then I get the following error:
`Expected a value that can be converted to type 'Int' but it was a 'LinkedHashMap'`

```
query GetItems( $limit: Int, $offset: Int) {
  items(
    pagination: {limit: $limit, offset: $offset} 
  ) {
      name
      color
  }
}
```

Input:
```
{
  "limit": 5,
  "offset": 0
}
```

But setting the whole input object like this works:
```
query GetItems( $pagination: PaginationInput) {
  items(
    pagination: $pagination
  ) {
      name
      color
  }
}
```

Input:
```
{
   "pagination": {
      "limit": 5,
      "offset": 0
  }
}

```

Setting the values directly in the query also works.
```
query GetItems {
  items(
    pagination: {limit: 2, offset: 0} 
  ) {
      name
      color
  }
}
```

It only fails in runtime so it is really hard to guard against as all these 3 queries are valid graphQL queries and I can't stop my users from writing their queries like that. 
The only work-around I found was to remove the default value completely from the GraphQLArgument and instead set the default if the argument is null. This comes with two downsides, defaultvalues will not show up in the schema definition and I have to add more code in my resolvers, so I would really appreciate another way of solving this.

Happy to provide more information if necessary and grateful for any help!

**Comment by kaqqao** [comment]
Thanks for the report!
graphql-java drastically changed how it handles default values and a lot of logic in SPQR had to be reimplemented. Somewhere in that migration your case fell through the cracks. I'll investigate what can be done.

**Comment by lindaandersson** [comment]
Thank you for your quick reply! It would be really appreciated :)

**Comment by kaqqao** [comment]
Oof, this is tricky business... Here's the breakdown.

In earlier versions, graphql-java permitted any Java object as the default value, and it would then do its best to represent such value in the serialized schema. And what SPQR did was simply deserialize the provided default value string into an object of the corresponding class and had it over to graphql-java. In your case, `{}` would deserialize to a `Pagination` instance, which would then get serialized back into schema as `{limit : 10, offset : 0}`.

Then, recent versions of graphql-java got rather strict and started only accepting values that can be unambiguously represented in the schema - in Java terms that would mean primitives, strings, lists and maps. No arbitrary Java objects allowed. So the way SPQR adapted was to deserialize the given default value to just the simple types mentioned previously. In your example, it means `{}` gets deserialized to an empty map, with gets serialized back into the schema as _nothing_.

At runtime, in both cases, you receive an equal instance of `Pagination`. This is because in the first case the default value is already a `Pagination` that simply gets passed, and in the second the default value is a map that gets converted into `Pagination` at each invocation. So the there should be no observable differences at runtime. But the printed schema is, as you've noticed, different.

I am not exactly sure yet how to approach this. It _sounds_ possible to emulate the earlier behavior of graphql-java by deserializing the provided default value string to an instance of the corresponding class just as before (thus triggering the appropriate constructor and populating the fields), but then convert it into a map before handing it back to graphql-java. This also sounds more correct, as the default values will get captured as they really are in Java. But I have to investigate a bit more to see if this indeed will not have any unwanted effects...

**Comment by kaqqao** [comment]
> This also sounds more correct, as the default values will get captured as they really are in Java. But I have to investigate a bit more to see whether this is indeed possible and will not have any unwanted effects.

On second though, this really isn't true, is it? After all, you're not surprised that you're seeing the following in your schema:

```graphql
input PaginationInput {
  limit: Int
  offset: Int
}
```

and not

```graphql
input PaginationInput {
  limit: Int = 10
  offset: Int = 0
}
```

despite 10 and 0 being the default for the corresponding Java fields, right? To achieve the latter, you'd have to do something like:

```java
public class Pagination {
        @GraphQLInputField(defaultValue = "10")
        public Integer limit = 10;
        @GraphQLInputField(defaultValue = "0")
        public Integer ffs = 0;
}
```
So why would you then be surprised to see 

```graphql
PaginationInput = {}
```

and not

```graphql
PaginationInput = {limit : 10, offset : 0}
```
when `{}` is what was explicitly specified? The above 2 cases are semantically equivalent, right?

**Comment by kaqqao** [comment]
I think the current behavior is consistent, so I'm inclined to leave it as-is. But, here's how you can pretty easily get the behavior you're after:

```java
public static class JsonReserializer implements DefaultValueProvider {

        private static final AnnotatedType OBJECT = TypeFactory.annotatedClass(Object.class, new Annotation[0]);

        private final ValueMapper valueMapper;

        public JsonReserializer() {
            this.valueMapper = Defaults.valueMapperFactory().getValueMapper();
        }

        @Override
        public DefaultValue getDefaultValue(AnnotatedElement targetElement, AnnotatedType type, DefaultValue initialValue) {
            // This is just guarding against freak cases, it's not strictly necessary
            if (initialValue.getValue() == null || initialValue.getValue().getClass() != String.class || type.getType() == String.class) {
                return initialValue;
            }
            return initialValue
                    .map(v -> valueMapper.fromString((String) v, type)) //String -> Pagination
                    .map(v -> valueMapper.fromInput(v, OBJECT)); //Pagination -> Map (as graphql-java wants it)
        }
    }
```

You can then either register this as the default provider, or use it where applicable only:

```java
@GraphQLQuery(name = "items")
        public CompletableFuture<List<RelayTest.Book>> items(
                @GraphQLArgument(
                        name = "pagination",
                        description = "Pagination of results.",
                        defaultValue = "{}",
                        defaultValueProvider = JsonReserializer.class)
                final Pagination pagination) {
            return ...;
        }
```

Note: Make sure `Pagination` has fields visible for serialization (e.g. make them public or have public getters). Previously `Pagination` instances were only ever deserialized, not they're being serialized as well.

Do you find this solution acceptable?

**Comment by kaqqao** [comment]
I managed to replicate this without SPQR, so it really is a bug in graphql-java. I opened an issue there: https://github.com/graphql-java/graphql-java/issues/3276

> With the new default value validation changes made in graphql-java, does this mean it is no longer recommended to send input values as objects?

Nothing perceivable should have changed, and I don't see anything wrong with how you're using the variables. Although, I must admit, all the examples online _always_ pass variables as arguments directly:

```graphql
query GetItems( $pagination: PaginationInput) {
  items(
    pagination: $pagination
  ) {
      name
      color
  }
}
```

but the spec seems to permit this as well:

```graphql
query GetItems( $limit: Int, $offset: Int) {
  items(
    pagination: {limit: $limit, offset: $offset} 
  ) {
      name
      color
  }
}
```

I talked about this in more detail in the linked graphql-java issue I opened.

I'll close this issue now as it seems the SPQR part has been addressed.

**Comment by lindaandersson** [comment]
Thank you! I should have checked that before reporting it to you. 

Looking forward to the new release with the fix!
