### ISSUE TITLE
Use @GraphQLContext for batching without @Batched

### ISSUE THREAD

**Issue by oleg-savko** [leangen/graphql-spqr#48]
Is exists way to use `@GraphQLContext` for batching not via `@Batched` annotation? 
For example for batching via [https://github.com/graphql-java/java-dataloader](dataloader)?

Or only one way to explicitly connect it via model?

**Comment by kaqqao** [comment]
`@Batched` is just a way to make use of the same semantics that `@Batched` already provides in graphql-java (note that it belongs to a graphql-java package, not SPQR). It provides a simple batching model that maps well to SQL (and some other) backends. It works with `BatchedExecutionStrategy` only.

Dataloader offers a very different strategy. To use dataloader, you must write the batch loader functions yourself and then change your logic to fetch data through the dataloader instead of directly. Unlike the previous model, it's not down to the execution strategy, but down to how you write your datafetchers. SPQR doesn't know what your methods do, so you need to change your own code to use the dataloader.

You might want to create a `DataLoaderRegistry` per request, and stick into the global context. This way you can easily inject it into your resolver methods via `@GraphQLRootContext`.
You must also make sure to register a `DataLoaderDispatcherInstrumentation` to dispatch the batch jobs. But this is all completely external to SPQR.

Keep in mind, SPQR only really deals with assembling the schema and wiring your methods as datafetchers. Actually executing the queries you do using graphql-java directly.

**Comment by kaqqao** [comment]
You can see a simple example of using `@Batched` in [BatchingTest](https://github.com/leangen/graphql-spqr/blob/master/src/test/java/io/leangen/graphql/BatchingTest.java)
