### ISSUE TITLE
Question about use of Subscription

### ISSUE THREAD

**Issue by fbrunosm** [leangen/graphql-spqr#58]
I'm try use Subscription, I define the subscription messageSubscription, but when I call saveMessage mutation the subscription don't fired. Do I need to add any annotation to the mutation so that it triggers the subscription event?

**Comment by kaqqao** [comment]
There's currently no event system built into SPQR, so you have to write this yourself. It only exposes the subscriptions as expected by graphql-java, but you have to implement the event publishing yourself.
If you're using Spring, it's pretty easy using Spring's event system. Otherwise, you need to develop a way some kind of event manager. One way to pass it around would be through the root context, so a mutation would resolver would acquire it via `@RootContext` and fire an event when needed.

I'm investigating whether SPQR could provide some facility around this or if it's too project-specific.

**Comment by fbrunosm** [comment]
I'm using Spring and try use Spring's event system. Thanks a lot and best regards

**Comment by kaqqao** [comment]
Keep me posted on what you end up doing :) Examples like that are _really_ valuable.
I'll look into it myself as well as soon as I get a chance.

**Comment by kaqqao** [comment]
Closing this one, as an example should be handled in the samples project.
