### ISSUE TITLE
Graphiql says "No Description" for type field despite description parameter in annotation is filled

### ISSUE THREAD

**Issue by DerTomm** [leangen/graphql-spqr#71]
Hi Bojan,

short question: Is it supposed that the "description" parameter of the @GraphQLQuery annotation is used as description for a type in the schema? If yes - shouldn't GraphiQL show that description? In my case I only see "No description" after clicking on a type in the schema browser.

**Comment by kaqqao** [comment]
The `description` from `@GraphQLQuery` should end up as the field description, while for a description of the type itself you'd commonly use one of `@GraphQLInterface` (placed on classes that are to be mapped as GraphQL interfaces), `@GraphQLUnion` (for Java interfaces that are to be mapped as unions in the schema) or `@GraphQLType` (for all other types).

All of these should be visible in GraphiQL, yes. If you're having issues, please provide a minimal example and I'll look into it.

**Comment by DerTomm** [comment]
So in my example I have the following POJO:
```
package foo.bar.domain;

import java.util.*;

import javax.persistence.*;

import io.leangen.graphql.annotations.GraphQLQuery;
import io.leangen.graphql.annotations.types.GraphQLType;
import lombok.*;

@Entity
@Table(name = "User")
@Data
@EqualsAndHashCode(callSuper = true)
@AllArgsConstructor
@NoArgsConstructor
@GraphQLType(name = "User", description = "User type")
public class User extends AbstractEntity {

  private static final long serialVersionUID = 1L;

  @Column(name = "username")
  @GraphQLQuery(description = "Username of the user.")
  private String username;

  // ... further fields ...

}
```
So I would expect that Graphiql shows "Username of the user." as description for the field "username" in the type "user".
The user type description is shown, but after clicking on "username" Graphiql says "No Description".

Did I make any mistake with the annotations or is the field description not processed properly during Schema creation?

**Comment by kaqqao** [comment]
Ah, I see. SPQR doesn't look at private fields, so what gets exposed is the generated getter which does not have the annotation, so no description is mapped.
Normally, SPQR will expose the annotated element, so if the annotation is on a field, the field will be queried directly, not through the getter. If the getter is annotated, it gets called. In your case, you have a generated public getter and a private annotated field. SPQR ignores private elements, so it only detects the getter without the annotation.

Since this mixture is quite expected for Lombok, I'll add support for it. In the meantime, I'm afraid you'd have to have explicit getters and place the annotations there...

As a side note, I've never seen so many annotations on a single class before :)

**Comment by DerTomm** [comment]
That makes sense. Thanks for adding Lombok support.

> As a side note, I've never seen so many annotations on a single class before :)

Yeah, another Lombok side effect :-)
