### ISSUE TITLE
Could @GraphQLNonNull be used as an ElementType.METHOD annotation?

### ISSUE THREAD

**Issue by vburlion** [leangen/graphql-spqr#91]
Everything is working great in our project with SPQR except for required fields : we're using Kotlin so getters/setters are generated, which makes it impossible to put the `@GraphQLNonNull` as parameter annotations.

Would it be possible to use this annotation as `ElementType.METHOD`?

Thanks!

**Comment by kaqqao** [comment]
I don't think this would actually solve your problem. `@GraphQLNonNull` is much more fine-grained, and can be used e.g. to produce nullable lists of non-nullable items, e.g. `List<@GraphQLNonNull Book>` which would be impossible to express.

Even if the annotation itself would be allowed on a method, much of the information would still be lost, due to [a bug](https://youtrack.jetbrains.com/issue/KT-13228) JetBrains doesn't care to fix. As a result, Kotlin properties simply don't work with Java's `TYPE_USE` annotations and `AnnotatedType` which are at the root of how SPQR works.

If I'd change the annotations, only _some_ cases would start working in Kotlin at the expense of creating long term complications and confusion. So it makes no sense from the project perspective to go there. I'm sorry to say, but with the situation as it is, Kotlin support is currently a non-goal. I'll do what I can to make it compatible where possible, but as long as the bug is there, I can't do all that much without sacrifices bigger than I'm willing to make...

**Comment by kaqqao** [comment]
The scariest part is that the property annotations are [inaccessible even to Kotlin's reflection](https://youtrack.jetbrains.com/issue/KT-16795). This one is even labeled as _Major_ priority, yet with no attention for over a year...

**Comment by vburlion** [comment]
@kaqqao sorry for the late answer and thank you for taking the time to explain what's happening with Kotlin. We'll write getters/setters manually.

**Comment by alediaferia** [comment]
Hey, I've created an example schema transformer that infers nullability information from Kotlin runtime.

You can have a look here: https://github.com/alediaferia/graphql-spqr-kotlin-example/blob/master/src/main/kotlin/com/alediaferia/graphql/spqr/kotlin/KotlinTypesSchemaTransformer.kt

@kaqqao let me know if there's anything you want me to include in the example and BTW: awesome work with this library, it's very well organized.

**Comment by williamboman** [comment]
@alediaferia Thank you for sharing this :heart:

**Comment by abdussametkaci** [comment]
> Hey, I've created an example schema transformer that infers nullability information from Kotlin runtime.
> 
> You can have a look here: https://github.com/alediaferia/graphql-spqr-kotlin-example/blob/master/src/main/kotlin/com/alediaferia/graphql/spqr/kotlin/KotlinTypesSchemaTransformer.kt
> 
> Have a look at the tests to better understand what it does.
> 
> @kaqqao let me know if there's anything you want me to include in the example and BTW: awesome work with this library, it's very well organized.

Hello, I saw your configuration and improved it a little more. I used your code as a source. So I wrote a configuration like this: [SchemaTransformerConfiguration](https://github.com/abdussametkaci/spring-boot-graphql-spqr-sample/blob/master/src/main/kotlin/com/example/springbootgraphqlspqrsample/configuration/SchemaTransformerConfiguration.kt)

Thanks for sharing :)
