### ISSUE TITLE
Excuse me, how to implement permission verification?

### ISSUE THREAD

**Issue by tianyafangcao** [leangen/graphql-spqr#92]
Now, I want to implement the different fields that are returned based on the roles used.

**Comment by kaqqao** [comment]
This is really in graphql-java territory.
You do this by providing a `GraphqlFieldVisibility` that decides what fields are visible. One way to this is SPQR is e.g.:

```java
generator.withSchemaProcessors((builder, context) -> builder.fieldVisibility(...))
```

You can also do this per-request (if you need the current user's roles) by transforming the base schema:

```java
schema.transform(builder -> builder.fieldVisibility(...))
```

This is a cheap operation, so can be safely done per-request.

**Comment by tianyafangcao** [comment]
Can annotations be implemented?

**Comment by tianyafangcao** [comment]
@kaqqao 
Returns the field dynamically based on the role.？
Can annotations be implemented?Is there a sample?

**Comment by kaqqao** [comment]
At this very moment, a custom annotation on a method _can_ be implemented, but is rather difficult and involves touching SPQR's internal API.

It would broadly go like this:
1. Make a custom `ResolverBuilder` and produce a custom subclass of `Resolver` that contains the annotation or the info needed from it
2. Implement `GraphqlFieldVisibility` as described above that:
 * casts `GraphQLFieldDefinition` to SPQR's internal `MappedGraphQLFieldDefinition` ((will break after SOQR is upgraded to 8.0!))
 * uses  `MappedGraphQLFieldDefinition#getOperation` to get a hold of the `Operation`
 * calls `Operation#getResolvers` to find all the resolvers attached to the operation (one `Resolver` = one method)
 * cast the `Resolver` to your subclass and extract the annotation/info you need

A much better route is to simply wait for SPQR to switch to graphql-java 8.0. It added runtime directive support, and I think I can use this to allow for much greater customizability in a standard way (independent of SPQR's internals).

So if you're not in a terrible rush, SPQR v0.9.8 will likely include the feature you want.

Also of interest, SPQR Spring Boot starter will at some point include integration with Spring Security annotations, so that the protected fields are hidden out of the box.
Of course, you can already use Spring Security to guard access, but you need a custom `GraphqlFieldVisibility` to hide the fields. This is what the starter will do automatically.

**Comment by ashifqureshi** [comment]
Hi,

When we can expect this feature to be available. 

Thank You!

**Comment by kaqqao** [comment]
See my [answer on StackOverflow](https://stackoverflow.com/a/51845557/294657). That should give you a good general idea on how to implement authorization.
Additionally, as of GraphQL SPQR 0.9.8, the `Operation` underlying each `GraphQLFieldDefinition` are accessible from a directive called `_mappedOperation`, argument `operation`.
A helper `Directives#getMappedOperation` will do this for you.

From the `Operation`, your instrumentation can access the underlying `Method`(s) and thus all the annotations on it. This way any metadata needed for authorization can be easily added.

**Comment by kaqqao** [comment]
I've just added a new feature, `ResolverInterceptor`s, that can be used to implement authorization _extremely simply_. See [this test](https://github.com/leangen/graphql-spqr/blob/master/src/test/java/io/leangen/graphql/InterceptorTest.java#L34) for an example doing exactly that.

Also see #180 some more context.

**Comment by kaqqao** [comment]
@KMUS  I think you're expecting the interceptor to trigger when input is being deserialized, which is not its intended purpose. In your example, the only resolver that ever fires in the `public String test(Bar bar)` method, so that's the only thing that gets intercepted. The `test` mutation returns a string (which is a scalar), so no further sub-selection is possible, so no further resolvers are triggered, and thus there's nothing else to intercept.
If you had a mutation like this:
```java
@Test(test = {"something"}) // this works
@GraphQLMutation
public Bar test(Bar bar) //Returns a Bar now
{
     return bar;
}
```
and a query string such as:
```graphql
mutation M {
    test(bar: {bar: "lala"}) {
        bar
    }
}
```
both the `test` method and `Bar#getBar` would get triggered and intercepted.

What I think you're expecting to happen is that `Bar#setBar` gets intercepted, but that method isn't a resolver for nay field, so `ResolverInterceptor` has no business intercepting it.

This would also quite difficult to implement generically, as it would require hooking into Jackson/Gson logic to intercept the deserialization (it's Jackson/Gson calling `Bar#setBar`). This is not to say its impossible, just... iffy business. And I'm not sure I understand the usecase...

What are you trying to achieve here? If you'd like to inspect the deserialized `Bar` instance given as the input, you already can: `InvocationContext#getArguments` gives access to all the provided arguments, so you can check if some IDs match or whatever...

**Comment by KMUS** [comment]
> 
> 
> @KMUS I think you're expecting the interceptor to trigger when input is being deserialized, which is not its intended purpose (it is a _resolver interceptor_ after all, ...

@kaqqao thanks for your comprehensive answer but let me more precise. My intention is to filter out attributes by permission. An user with admin privileges is only allowed to set und get bar1, an user with user privileges only bar2.

```
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.FIELD})
public @interface Auth
{
    String[] permission();
}

public class Foo
{
    @Auth(permission = "admin")
    public String getBar1()
    {
        return bar1;
    }

    @Auth(permission = "admin")
    public void setBar1(String bar1)
    {
        this.bar1 = bar1;
    }

    @Auth(permission = "user")
    public String getBar2()
    {
        return bar2;
    }

    @Auth(permission = "user")  
    public void setBar2(String bar2)
    {
        this.bar2 = bar2;
    }
    String bar1;
    String bar2;
}

@GraphQLMutation
public Foo test(@GraphQLArgument(name = "foo") Foo foo)
{
    return foo;
}
```

If an admin calls **test(foo: {bar1: "47", bar2: "11"})**, it results in input and output bar1 = 47, everything else is filtered out and for user **test(foo: {bar1: "47", bar2: "11"})** it means bar2 = 11. 

Neither instrumentation nor field visibility is helpful because I need access to the auth annotation to make my filter decissions. Is there any elegant way to solve my problem?

**Comment by kaqqao** [comment]
Controlling inputs is really the job for `GraphqlFieldVisibility`. It doesn't make much sense to enable the user to send a field, but then just disregard in the backend.

Unfortunately, SPQR doesn't keep the underlying `InputField` when building `GraphQLInputObjectField`s (like it does for `GraphQLFieldDefinition`, where the underlying `Operation` is kept in a directive).

I've just pushed a change that adds that feature for the next release #216. For the moment, you can maybe work around it by implementing `GraphqlFieldVisibility` like this:

```java
public static class CustomVisibility extends DefaultGraphqlFieldVisibility {

        @Override
        public GraphQLInputObjectField getFieldDefinition(GraphQLInputFieldsContainer fieldsContainer, String fieldName) {
            GraphQLInputObjectField field = super.getFieldDefinition(fieldsContainer, fieldName);
            Class<?> objectJavaType = ClassUtils.getRawType(Directives.getMappedType(fieldsContainer).getType());
            Optional<Method> getter = ClassUtils.findGetter(objectJavaType, fieldName);
            Optional<Method> setter = getter.flatMap(m -> ClassUtils.findSetter(objectJavaType, fieldName, m.getReturnType()));
            ...; //Get the annotations from getter/setter and make a decision whether to return the field or null
            return field;
        }
    }
```

**Comment by kaqqao** [comment]
The unfortunate thing here is that `GraphqlFieldVisibility` goes on a schema, forcing you to transform it every time and rebuild `GraphQL`. It would be much better if it went into the `ExecutionInput`.
I'll see if it's possible to move it there...

**Comment by KMUS** [comment]
@kaqqao thanks for your effort, works like intended except that this workaround only works for pojos without lombok @Getter/Setter support but that is neglectable.

**Comment by kaqqao** [comment]
@KMUS Well, nothing's preventing you from looking at the field directly, instead of getter/setter. You can use `ClassUtils.findField(objectJavaType, fieldName)` for that.

**Comment by KMUS** [comment]
@kaqqao is there a way to access the GraphQLRootContext in CustomVisibility because it holds my current user object or is a parameterized ctor the only solution?
